### PR TITLE
Fix for ancient libc build

### PR DESCRIPTION
**Pull request by Keno**

### CODE REVIEW

**Comment by khuey** [comment]
Yikes that's old.

**Comment by Keno** [comment]
Our (julia) platform support policy includes CentOS 6, which has libc from 2010, so we test this path in our deployment scripts.

**Comment by khuey** [comment]
How does that have a kernel new enough for rr?

**Comment by Keno** [comment]
Usually people run it in a docker container on a modern kernel.

**Comment by khuey** [comment]
Ah.

**Pull request merged**
