### PR TITLE
testsuite: add LC_ALL default to util.sh

### LINKED ISSUE #3545: Test 'madvise_dontfork' FAILED: debug script failed
Ran tests with current master.

Kernel: Linux 4.18.0-80.el8.x86_64
gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
GNU assembler version 2.30-79.el8

~~~
0% tests passed, 2 tests failed out of 2

Total Test time (real) = 248.89 sec

The following tests FAILED:
        1046 - madvise_dontfork (Failed)
        1047 - madvise_dontfork-no-syscallbuf (Failed)
Errors while running CTest
~~~

### PR DESCRIPTION
**Pull request by GitMensch**
The testsuite should run on any system with different settings, so create a reasonable default for all tests.

fixes #3545

### CODE REVIEW

**Comment by bernhardu** [comment]
Seems CI reports with this change for madvise_dontfork a ["timeout 120 exceeded"](https://buildkite.com/julialang/rr/builds/1248#01892f99-9b96-479d-91d0-a2e30211c879/6-12980).

**Comment by GitMensch** [comment]
yay, I only get a timeout if I don't use that :-/

**Comment by dzaima** [comment]
This is in the log:
```
warning: setlocale: LC_ALL: cannot change locale (C.utf8): No such file or directory
```
So the CI doesn't have the `C.utf8` locale. So an option that'd at least ignore that would be putting the `LC_ALL=C.utf8` behind a check of `locale -a | grep C.utf8` or something. Of course that'd make it not properly set it on systems where it doesn't exist, but that'd at least not be a guaranteed failure.

**Comment by bernhardu** [comment]
I did parallel a few tests and this is the output of a [`ls -lisah /usr/lib/locale`](https://buildkite.com/julialang/rr/builds/1252#0189326a-6a03-4295-92d4-2d5e92ad9d85/596-597) and [`locale -a`](https://buildkite.com/julialang/rr/builds/1252#0189326a-6a03-4295-92d4-2d5e92ad9d85/596-602) from a CI system.
And it looks like at the CI system there is just a "C.UTF-8" while e.g. at my local Debian system there is just a "C.utf8".
I guess a solution could be to use `export LC_ALL=$(locale -a | grep -i -E "^C.utf")`, at least my last attempt in my test [PR 3552](https://www.github.com/rr-debugger/rr/pull/3552) succeeded.

**Comment by GitMensch** [comment]
Thank you for inspecting this further! I'll do some tests later, then amend the commit to use that approach (also testing for 8 to ensure we don't set it to utf16).

**Comment by bernhardu** [comment]
> also testing for 8 to ensure we don't set it to utf16

Then maybe `locale -a | grep -i -E "^C\.utf.*8$"` might do it? (Also added `\` for the dot.)

**Comment by bernhardu** [comment]
But now I see it - the environment shows [`LANG=en_US.UTF-8`](https://buildkite.com/julialang/rr/builds/1252#0189326a-6a03-4295-92d4-2d5e92ad9d85/395-558), but it looks like the available locale is [`en_US.utf8`](https://buildkite.com/julialang/rr/builds/1252#0189326a-6a03-4295-92d4-2d5e92ad9d85/596-604). Is this maybe the original cause?

**Comment by bernhardu** [comment]
Now I see at my local system I have the same difference, just with de_DE....
And the test works with LANG set in both ways in my Debian Bookworm system.
From reading [this discussion](https://serverfault.com/questions/616744/is-there-a-difference-between-en-us-utf8-and-en-us-utf-8) it looks like `en_US.UTF-8` should be valid ...

In [run 1255](https://buildkite.com/julialang/rr/builds/1255#01893492-d8a3-48f2-83f7-72040203cfbe/398-399) I even found CI defines `LANG=en_US.UTF-8`, which is reported by `locales -a`,
but does not even exist below `/usr/lib/locale`.

**Comment by bernhardu** [comment]
Can you provide the values of your LANG, LANGUAGE, LC_ALL, LCTYPE, and some details about your system?

**Comment by rocallahan** [comment]
FYI I moved this Unicode stuff to its own test in 9e1101a3c18ddef11df507cca911858c155f2084

**Comment by GitMensch** [comment]
Should the LC setting only be done in unicode.run or is it still fine to add that to util.sh?

**Comment by rocallahan** [comment]
Probably only unicode.run if it requires running a subprocess to figure out which setting to use.

**Comment by GitMensch** [comment]
The normal build now works fine, so it seems the change to util.sh is fine.

**Comment by GitMensch** [comment]
@rocallahan Thanks for splitting the unicode test out. As we found that the "simple" setting works and we don't need to run any subcommands I've opted to add it to util.h, leading to both GH CI and the local build to work fine.

**Pull request merged**
