### PR TITLE
CI: Print CPU information at the beginning of the job

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@Keno @vtjnash

**Comment by DilumAluthge** [comment]
Ah, `lscpu` doesn't work inside the sandbox, which is probably a good think.

I don't think it's worth trying to get `lscpu` working inside the sandbox.

Instead, if a job is failing, and someone wants to know which CPU that job ran on, just ping me or @Keno - we can SSH into the machine and run `lscpu` outside the sandbox, and then provide that information to you.

**Comment by khuey** [comment]
Seems like you ought to be able to run `cpuid -1`, or just `cat /proc/cpuinfo` or something.

**Comment by DilumAluthge** [comment]
`cpuid -1` doesn't work inside the sandbox, but `cat /proc/cpuinfo` does!

**Comment by khuey** [comment]
`awk -v RS= 'NR==1' /proc/cpuinfo` is probably better than straight `cat` since it'll avoid repeating for each CPU

**Comment by DilumAluthge** [comment]
@Keno This one is also good to go.

**Comment by DilumAluthge** [comment]
Bump @Keno

**Pull request merged**
