### PR TITLE
CI: update the `glibc` version we use for `aarch64`

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
Hat-tip @staticfloat for providing this fix.

**Comment by DilumAluthge** [comment]
Okay, so the original issue (the `glibc` problem) seems to be fixed. But now there's a new test failure.

@Keno Is this test failure expected?

**Comment by Keno** [comment]
The glibc that comes with the rootfs likely wasn't built with `-moutline-atomics` (or more likely with a GCC version that doesn't have the initializer priority fix) which is required for rr to work. I think the way to fix this will be to bump the glibc version in Yggdrasil and then bumping the version here. Yggdrasil builds these things with rr compatibility.

**Comment by rocallahan** [comment]
So the patched glibc didn't work with the version of lldb or its dependencies that you tried to install? Can we just install a different version of lldb and not upgrade glibc?

**Comment by Keno** [comment]
We periodically bump the base debian version that we use to build the CI root images, but we didn't bump the rr ci config when that happened last, so it was still on old debian. So the new debian has a newer glibc than the patched one that we had prepared for rr. We could build an old debian with lldb, but I think building newer glibc is probably easier, since that's all automated. Otherwise the rr ci would need a special snowflake rootfs build for the older debian.

**Comment by Keno** [comment]
@DilumAluthge do you know what needs to be done for the glibc bump or do you need me to take care of it?

**Comment by rocallahan** [comment]
Looks like this PR is still failing.

I know you guys are busy but I hope we can get this fixed

**Comment by DilumAluthge** [comment]
> The CI setup on this repo has changed - we no longer use Buildkite, so this PR is stale.

**Pull request closed without merging**
