### PR TITLE
Restructure Android build with a Dockerfile.

### PR DESCRIPTION
**Pull request by DanAlbert**
Remove the "works on my machine" guesswork. This keeps all the Android parts of the build in build.sh, but moves all the host dependencies (including the capnproto fetch) into the Dockerfile.

This cleans up some of the header/library directory handling as well, which was necessary for making the build script work when the host and target builds are separate (CAPNP_CFLAGS doesn't actually exist, so the build was previously finding the host's includes by coincidence?)

@khuey wdyt? This was a byproduct of me trying to debug https://github.com/rr-debugger/rr/pull/3432. It's helpful to me as someone that doesn't actually know much about building rr, but if it's just going to be in your way we should probably just close this :)

(in any case, it's not ready to submit yet as the Android CI script will need to be updated to account for this)

### CODE REVIEW

**Comment by khuey** [comment]
This seems generally sensible. My only comment is that perhaps we should make an ndk_version arg like the cloudbuild Dockerfile does.

https://github.com/GoogleCloudPlatform/cloud-builders-community/blob/1dbc67888a7c3f2e17fe3c17ce6646572fa228e3/android/Dockerfile-ndk

**Comment by DanAlbert** [comment]
Sorry for the delay, took me a while to get back to this. Good idea :) Updated the PR.

**Comment by DanAlbert** [comment]
(keeping this as a draft until I'm more confident that we'll actually be able to use this on our side)

**Comment by DanAlbert** [comment]
I unfortunately won't be able to use this (or anything else that we can do upstream) on our end, because the build that android will use now needs to be built by android infrastructure, and that won't map well into other CI systems (it could be made to with some effort, but not well).

That said, this is possibly worth checking in anyway. The Android build was broken by 7de81f75517f18b9078e4199dfd50d6c23c8512c (android does not have `pthread_attr_setsigmask_np`), and it'd probably save everyone time if we checked the Android build in a github action or similar? If that works for you, let's check this in and I'll follow up with a PR to add the GHA. If you prefer buildkite I'll leave that to you though since I don't know that system :)

(sorry for all the churn here, fwiw it's frustrating for me too)

**Comment by rocallahan** [comment]
> The Android build was broken by [7de81f7](https://github.com/rr-debugger/rr/commit/7de81f75517f18b9078e4199dfd50d6c23c8512c) (android does not have `pthread_attr_setsigmask_np`),

That got fixed in https://github.com/rr-debugger/rr/commit/56e845132af7885dca06ed08d08d19b43e8d1e26.

A Github action that checks that Android builds would probably be worth having.

**Comment by DanAlbert** [comment]
Ah, thanks! I haven't synced in a few days and I guess I just got lucky and synced while it was briefly broken :)

**Comment by DanAlbert** [comment]
Added a second commit which includes the github action. Once that goes green (there's no way to test those locally, so I'll be iterating here if it isn't already, but this is more or less exactly what I'd tested in https://github.com/DanAlbert/rr/tree/slsa so it should be at least close), this is ready to submit as far as I'm concerned.

**Comment by DanAlbert** [comment]
Whoops, sorry, an extra commit got mixed in. Removed that.

**Comment by khuey** [comment]
This looks fine to me. Is it ready to go for you?

**Comment by DanAlbert** [comment]
Yep. Ship it :)

**Pull request merged**
