### PR TITLE
Avoid incompatiblities between newer glibc <sys/mount.h> and <linux/mount.h> include and needed <time.h>

### PR DESCRIPTION
**Pull request by wcohen**
When building on rr Fedora rawhide the newer version of glibc <sys/mount.h> is incompatible with <linux/mount.h>  The following URL suggests using one include or the other:

https://sourceware.org/glibc/wiki/Release/2.36#Usage_of_.3Clinux.2Fmount.h.3E_and_.3Csys.2Fmount.h.3E

It appears that removed <linux/mount.h> pulled in some <time.h> declarations, so needed to add a <time.h> include to test-monitor.cc

These patches have been check on Fedora 36 and Fedora Rawhide.

### CODE REVIEW

**Comment by rocallahan** [comment]
This failed to build in CI, can you take a look?

**Comment by wcohen** [comment]
In Fedora rawhide packages are compiled with -Wall, but not -Werror=implicit-function-declaration.  See the same messages as warnings on the Fedora rawhide builds with the patches (https://koji.fedoraproject.org/koji/buildinfo?buildID=2043181):

aarch64: https://kojipkgs.fedoraproject.org//packages/rr/5.6.0/1.fc37/data/logs/aarch64/build.log
x86_64: https://kojipkgs.fedoraproject.org//packages/rr/5.6.0/1.fc37/data/logs/x86_64/build.log

/usr/include/sys/mount.h has declaration for function 'mount'.  With that header removed the implicit declaration warning/error is triggered. Look the patch will need to be reworked.

**Comment by wcohen** [comment]
The <sys/mount.h> provides the declaration for function 'mount' as mentioned on the man page. Maybe put in declaration of mount in util.h.  With glibc-2.36 there were incompatibilities with including both <sys/mount.h> and <linux/mount.h> in the same file as seen with building rr without the mount include removed in rawhide (https://koji.fedoraproject.org/koji/taskinfo?taskID=90710983).  On x86_64 see the following in the build log:
```
/usr/bin/gcc -DEXECINFO_H=1 -DFANOTIFY_H=1 -DMQUEUE_H=1 -DPROC_SERVICE_H=1 -DRR_VERSION=\"5.6.0\" -I/builddir/build/BUILD/rr-5.6.0/include -I/builddir/build/BUILD/rr-5.6.0/third-party/proc-service -I/builddir/build/BUILD/rr-5.6.0/third-party/brotli/include -I/builddir/build/BUILD/rr-5.6.0/redhat-linux-build -I/builddir/build/BUILD/rr-5.6.0/src/preload -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1  -m64  -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D__USE_LARGEFILE64 -pthread -msse2 -D__MMX__ -D__SSE__ -D__SSE2__ -fmacro-prefix-map=/builddir/build/BUILD/rr-5.6.0/= -Wstrict-prototypes -std=gnu11  -pthread  -DNDEBUG -Wall -Wextra -DDEBUG -UNDEBUG -g3 -O0 -MD -MT CMakeFiles/64bit_child.dir/src/test/64bit_child.c.o -MF CMakeFiles/64bit_child.dir/src/test/64bit_child.c.o.d -o CMakeFiles/64bit_child.dir/src/test/64bit_child.c.o -c /builddir/build/BUILD/rr-5.6.0/src/test/64bit_child.c
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdlib.h:26,
                 from /builddir/build/BUILD/rr-5.6.0/src/test/util.h:15,
                 from /builddir/build/BUILD/rr-5.6.0/src/test/64bit_child.c:3:
/usr/include/features.h:412:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
  412 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
      |    ^~~~~~~
In file included from /usr/include/linux/fs.h:19,
                 from /usr/include/linux/aio_abi.h:31,
                 from /builddir/build/BUILD/rr-5.6.0/src/test/util.h:29:
/usr/include/linux/mount.h:95:6: error: redeclaration of 'enum fsconfig_command'
   95 | enum fsconfig_command {
      |      ^~~~~~~~~~~~~~~~
In file included from /builddir/build/BUILD/rr-5.6.0/src/test/util.h:17:
/usr/include/sys/mount.h:189:6: note: originally defined here
  189 | enum fsconfig_command
      |      ^~~~~~~~~~~~~~~~
/usr/include/linux/mount.h:96:9: error: redeclaration of enumerator 'FSCONFIG_SET_FLAG'
   96 |         FSCONFIG_SET_FLAG       = 0,    /* Set parameter, supplying no value */
      |         ^~~~~~~~~~~~~~~~~
/usr/include/sys/mount.h:191:3: note: previous definition of 'FSCONFIG_SET_FLAG' with type 'enum fsconfig_command'
  191 |   FSCONFIG_SET_FLAG       = 0,    /* Set parameter, supplying no value */
      |   ^~~~~~~~~~~~~~~~~
/usr/include/linux/mount.h:97:9: error: redeclaration of enumerator 'FSCONFIG_SET_STRING'
   97 |         FSCONFIG_SET_STRING     = 1,    /* Set parameter, supplying a string value */
      |         ^~~~~~~~~~~~~~~~~~~
/usr/include/sys/mount.h:193:3: note: previous definition of 'FSCONFIG_SET_STRING' with type 'enum fsconfig_command'
  193 |   FSCONFIG_SET_STRING     = 1,    /* Set parameter, supplying a string value */
      |   ^~~~~~~~~~~~~~~~~~~
/usr/include/linux/mount.h:98:9: error: redeclaration of enumerator 'FSCONFIG_SET_BINARY'
   98 |         FSCONFIG_SET_BINARY     = 2,    /* Set parameter, supplying a binary blob value */
      |         ^~~~~~~~~~~~~~~~~~~
/usr/include/sys/mount.h:195:3: note: previous definition of 'FSCONFIG_SET_BINARY' with type 'enum fsconfig_command'
  195 |   FSCONFIG_SET_BINARY     = 2,    /* Set parameter, supplying a binary blob value */
      |   ^~~~~~~~~~~~~~~~~~~
/usr/include/linux/mount.h:99:9: error: redeclaration of enumerator 'FSCONFIG_SET_PATH'
   99 |         FSCONFIG_SET_PATH       = 3,    /* Set parameter, supplying an object by path */
      |         ^~~~~~~~~~~~~~~~~
/usr/include/sys/mount.h:197:3: note: previous definition of 'FSCONFIG_SET_PATH' with type 'enum fsconfig_command'
  197 |   FSCONFIG_SET_PATH       = 3,    /* Set parameter, supplying an object by path */
      |   ^~~~~~~~~~~~~~~~~
/usr/include/linux/mount.h:100:9: error: redeclaration of enumerator 'FSCONFIG_SET_PATH_EMPTY'
  100 |         FSCONFIG_SET_PATH_EMPTY = 4,    /* Set parameter, supplying an object by (empty) path */
      |         ^~~~~~~~~~~~~~~~~~~~~~~
/usr/include/sys/mount.h:199:3: note: previous definition of 'FSCONFIG_SET_PATH_EMPTY' with type 'enum fsconfig_command'
  199 |   FSCONFIG_SET_PATH_EMPTY = 4,    /* Set parameter, supplying an object by (empty) path */
      |   ^~~~~~~~~~~~~~~~~~~~~~~
/usr/include/linux/mount.h:101:9: error: redeclaration of enumerator 'FSCONFIG_SET_FD'
  101 |         FSCONFIG_SET_FD         = 5,    /* Set parameter, supplying an object by fd */
      |         ^~~~~~~~~~~~~~~
/usr/include/sys/mount.h:201:3: note: previous definition of 'FSCONFIG_SET_FD' with type 'enum fsconfig_command'
  201 |   FSCONFIG_SET_FD         = 5,    /* Set parameter, supplying an object by fd */
      |   ^~~~~~~~~~~~~~~
/usr/include/linux/mount.h:102:9: error: redeclaration of enumerator 'FSCONFIG_CMD_CREATE'
  102 |         FSCONFIG_CMD_CREATE     = 6,    /* Invoke superblock creation */
      |         ^~~~~~~~~~~~~~~~~~~
/usr/include/sys/mount.h:203:3: note: previous definition of 'FSCONFIG_CMD_CREATE' with type 'enum fsconfig_command'
  203 |   FSCONFIG_CMD_CREATE     = 6,    /* Invoke superblock creation */
      |   ^~~~~~~~~~~~~~~~~~~
/usr/include/linux/mount.h:103:9: error: redeclaration of enumerator 'FSCONFIG_CMD_RECONFIGURE'
  103 |         FSCONFIG_CMD_RECONFIGURE = 7,   /* Invoke superblock reconfiguration */
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/sys/mount.h:205:3: note: previous definition of 'FSCONFIG_CMD_RECONFIGURE' with type 'enum fsconfig_command'
  205 |   FSCONFIG_CMD_RECONFIGURE = 7,   /* Invoke superblock reconfiguration */
      |   ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/linux/mount.h:129:8: error: redefinition of 'struct mount_attr'
  129 | struct mount_attr {
      |        ^~~~~~~~~~
/usr/include/sys/mount.h:161:8: note: originally defined here
  161 | struct mount_attr
      |        ^~~~~~~~~~
```

**Comment by wcohen** [comment]
It looks like the glibc/linux-head incompatibility has been addressed and pulled into glibc-2.36 as the following has that marked out in:

https://sourceware.org/glibc/wiki/Release/2.36#Usage_of_.3Clinux.2Fmount.h.3E_and_.3Csys.2Fmount.h.3E

Also see the patches have been pulled into Fedora rawhide:

https://src.fedoraproject.org/rpms/glibc/c/ae30d62333ba0c18ee2cf1a39de04185a4422823?branch=rawhide

**Comment by rocallahan** [comment]
So we don't need to do anything here, right?

**Comment by wcohen** [comment]
That is correct. It looks like changes to glibc eliminated this problem, so no changes to rr are needed.

**Comment by rocallahan** [comment]
Great, thanks.

**Pull request closed without merging**
