### PR TITLE
buildkite: Install libzstd-dev package.

### PR DESCRIPTION
**Pull request by bernhardu**
This is needed since f289046a2.

### CODE REVIEW

**Comment by rocallahan** [comment]
Are you still running your own Buildkite CI?

**Comment by bernhardu** [comment]
No, I was just looking at the [julialang buildkite](https://buildkite.com/julialang/rr/builds).

**Comment by rocallahan** [comment]
We don't need to use Buildkite anymore. I've asked Keno and Dilium to turn down the Buildkite runners.

**Comment by bernhardu** [comment]
Ah, ok, somehow I missed this is now covered by the Github Actions. Thanks, closing this PR.

**Pull request closed without merging**
