### PR TITLE
Add Intel Tremont

### PR DESCRIPTION
**Pull request by Frederick888**
The cpu_type is from an Intel N6005 [1].

[1] https://www.intel.com/content/www/us/en/products/sku/212327/intel-pentium-silver-n6005-processor-4m-cache-up-to-3-30-ghz/specifications.html

---

Recently got my hands on a new board with this chip. Since it's a successor
of Goldmont Plus, I gave the same configuration a shot and it looked ok(?)

Failed tests:

```
The following tests FAILED:
	468 - prctl (Failed)
	469 - prctl-no-syscallbuf (Failed)
	724 - sioc (Failed)
	725 - sioc-no-syscallbuf (Failed)
	1140 - x86/string_instructions_replay (Failed)
	1141 - x86/string_instructions_replay-no-syscallbuf (Failed)
	1144 - x86/string_instructions_watch (Failed)
	1145 - x86/string_instructions_watch-no-syscallbuf (Failed)
	1388 - x86/string_instructions_break (Failed)
	1389 - x86/string_instructions_break-no-syscallbuf (Failed)
	1390 - x86/string_instructions_replay_quirk (Failed)
	1391 - x86/string_instructions_replay_quirk-no-syscallbuf (Failed)
	1892 - prctl-32 (Failed)
	1893 - prctl-32-no-syscallbuf (Failed)
	2564 - x86/string_instructions_replay-32 (Failed)
	2565 - x86/string_instructions_replay-32-no-syscallbuf (Failed)
	2568 - x86/string_instructions_watch-32 (Failed)
	2569 - x86/string_instructions_watch-32-no-syscallbuf (Failed)
	2812 - x86/string_instructions_break-32 (Failed)
	2813 - x86/string_instructions_break-32-no-syscallbuf (Failed)
	2814 - x86/string_instructions_replay_quirk-32 (Failed)
	2815 - x86/string_instructions_replay_quirk-32-no-syscallbuf (Failed)

```

Full log: [rr_check.log](https://github.com/rr-debugger/rr/files/10121994/rr_check.log)

### CODE REVIEW

**Comment by Keno** [comment]
String instructions test failure seems problematic and worth digging into. The string instructions are also particularly sensitive to microarchitecture differences, so it's not a huge surprise.

**Comment by Frederick888** [comment]
@Keno Thanks for the feedback! Though I'm to be honest quite clueless about these. Here's the [LastTest.log](https://github.com/rr-debugger/rr/files/10123594/LastTest.log). Can this be something helpful?

**Comment by GitMensch** [comment]
There were a bunch of x86 changes recently. @Frederick888 would you mind to rebase and retest?

**Comment by GitMensch** [comment]
LGTM, as this does not add another cpuid but only fixes the arch behind that, I suggest to pull it in as-is. @Keno can you do that?

**Comment by Frederick888** [comment]
@GitMensch Yup it was added in ed1ab9bfe3f3ea05f5b03006382efc4d9ccf89d3 for N5095, which is also Tremont according to https://en.wikipedia.org/wiki/Tremont_(microarchitecture).

And test results:

```
The following tests FAILED:
	742 - sioc (Failed)
	743 - sioc-no-syscallbuf (Failed)
	954 - clone_file_range (Failed)
	955 - clone_file_range-no-syscallbuf (Failed)
	1174 - x86/string_instructions_replay (Failed)
	1175 - x86/string_instructions_replay-no-syscallbuf (Failed)
	1178 - x86/string_instructions_watch (Failed)
	1179 - x86/string_instructions_watch-no-syscallbuf (Failed)
	1434 - x86/string_instructions_break (Failed)
	1435 - x86/string_instructions_break-no-syscallbuf (Failed)
	1436 - x86/string_instructions_replay_quirk (Failed)
	1437 - x86/string_instructions_replay_quirk-no-syscallbuf (Failed)
	2428 - clone_file_range-32 (Failed)
	2429 - clone_file_range-32-no-syscallbuf (Failed)
	2648 - x86/string_instructions_replay-32 (Failed)
	2649 - x86/string_instructions_replay-32-no-syscallbuf (Failed)
	2652 - x86/string_instructions_watch-32 (Failed)
	2653 - x86/string_instructions_watch-32-no-syscallbuf (Failed)
	2908 - x86/string_instructions_break-32 (Failed)
	2909 - x86/string_instructions_break-32-no-syscallbuf (Failed)
	2910 - x86/string_instructions_replay_quirk-32 (Failed)
	2911 - x86/string_instructions_replay_quirk-32-no-syscallbuf (Failed)
```
[rr_check.log](https://github.com/rr-debugger/rr/files/13174432/rr_check.log)

**Comment by GitMensch** [comment]
Thank you for the update.

Please create a new issue "failing tests string_instructions on Intel Tremont" attaching the log file from `ctest --rerun-failed -VV` along with the output of `uname -rv && cat /etc/*release*`, so this can be inspected further (the log file above only contains the test runs, not the detailed failures).

**Comment by khuey** [comment]
I don't think we should merge this until we sort out the string instruction issue.

**Comment by GitMensch** [comment]
Note: after the referenced PR, there is already Tremont support, even this specific cpuid!

Now this PR adds only the missing pieces to handle and report the microarch correctly.

I'm quite confident that the string test also would have failed with the cpu in the other "not that clean" PR, there were just no questions asked.

And for the falling string test itself, we now have a separate issue.

**Comment by khuey** [comment]
I suppose we may as well merge this since #3624 got merged but it really would be good if the string instructions got fixed ....

**Pull request merged**
