### PR TITLE
add support for HIDIOCGRDESC and an unrecognized ioctl (from a driver?)

### PR DESCRIPTION
**Pull request by db48x**
I haven’t investigated where the other one comes from.

### CODE REVIEW

**Comment by rocallahan** [comment]
I'd really like to have a test and know what the other ioctl is.

**Comment by db48x** [comment]
Pretty sure it’s an nvidia thing; that’s the only source of out–of–kernel modules I have. Do you know of a way to verify that?

Also, what kind of test would you like? I see several that are related to specific kinds of ioctls, such as joysticks and networking, but they appear to test that the ioctls actually work. That is, that they can be used to add addresses to interfaces and then remove them; presumably this is testing that rr can handle these ioctls in the same manner that the kernel would without actually sending them to the kernel. I can’t do that for an undocumented nvidia–specific ioctl.

**Comment by rocallahan** [comment]
How about `HIDIOCGRDESC`? Let's tackle that first before worrying about the undocumented one.

We try to block opens of the NVidia device so I don't think we should be seeing ioctls on it.

**Comment by db48x** [comment]
All rr does for HIDIOCGRDESC is reserve space to hold whatever data is being sent, right? Is there another test that verifies that?

**Comment by rocallahan** [comment]
> All rr does for HIDIOCGRDESC is reserve space to hold whatever data is being sent, right? Is there another test that verifies that?

Ideally we'd have a test that opens a HID device (if one can be found) and performs the ioctl on it, storing the results in a struct allocated with `ALLOCATE_GUARD` and then verifying that the results are sane --- just printing them is good enough, since that will almost certainly cause divergence if we fail to replay the results correctly.

**Comment by db48x** [comment]
Ah, that explains why a lot of these tests just print stuff out rather than asserting them directly. `ioctl_vt.c` looks simple enough; I’ll write a test modeled on it and see how it goes.

**Comment by db48x** [comment]
/me grumbles

There’s a sample program in the kernel source which uses HIDIOCGRDESCSIZE and HIDIOCGRDESC to print out the descriptor, but in my test the latter fails with an invalid argument error. The code is virtually identical, so it must be a pretty stupid error.

I’ll have to sleep on it.

**Comment by db48x** [comment]
Yea, it was a pretty stupid error.

**Comment by rocallahan** [comment]
Thanks. Can you open another issue for the ioctl? Maybe you can use lsof and run under gdb without rr to determine what file the ioctl is on?

**Pull request merged**
