### PR TITLE
[RFC] Add some syscalls needed by Xorg

### PR DESCRIPTION
**Pull request by bernhardu**
This pull request contains a some syscall modifications, which enabled me to record a Xorg process running as root inside a (non GPU accellerated) Qemu VM.
Should these put their test all in separate files or into which tests would they match?
Should the patches be split up differently?

### CODE REVIEW

**Comment by rocallahan** [comment]
These all look fine as-is, except for one thing: if an application uses `ioperm`/`iopl`, then does an `OUT` instruction, during recording that will work properly, but during replay I think the `OUT` instruction will trigger a GP fault. So I don't understand how an application using `ioperm`/`iopl` would actually work under rr. Also `iopl` is supposed to enable userspace to execute `CLI`, but that would also generate a GP fault during rr replay. So how does this work?

**Comment by bernhardu** [comment]
I could not find any more issues replaying, also with one real hardware system.
Tried also to find some out or cli instructions via objdump, but never hit one of the resulting functions when replaying.
So might one possible explanation be, they are just leftovers in Xorg and not needed anymore for operation (at x86_64)?

**Comment by rocallahan** [comment]
It's a bit unfortunate if `iopl`/`ioperm` are "supported" in rr but only if you don't actually *use* them.

**Comment by rocallahan** [comment]
Oh well, let's do this. If we need to do something about this during replay we'll cross that bridge when we come to it. (I think we could detect a SIGSEGV on a CLI/STI/OUT instruction and just skip the instruction during replay.)

**Comment by rocallahan** [comment]
Thanks!

**Pull request merged**
