### PR TITLE
Save interpreter_base and ld_path at AddressSpace construction.

### PR DESCRIPTION
**Pull request by bernhardu**
This aids compatibility with GDB 10.1.
Related issue #2740.

### CODE REVIEW

**Comment by rocallahan** [comment]
This looks good. Ideally we'd also have a test for this. The test would use iterate_maps to search for the interpreter mapping and unmap its first page, I guess, and we'd need a gdb script.

**Comment by rocallahan** [comment]
I think in this case I'm going to ask nicely for a test but not require it if it's too hard.

**Comment by bernhardu** [comment]
Let me have a look, but might take some time.

**Comment by bernhardu** [comment]
The added test invalid_interpreter fails at x86_64 if the first patch to rr is not applied, but succeeds if both patches are applied.
The test invalid_interpreter-32 succeeded already before.
Is this somewhere near what you had in mind?

**Comment by rocallahan** [comment]
Great thanks.

**Pull request merged**
