### PR TITLE
Use a call rather than a jump to get to the _dl_runtime_resolve patch.

### LINKED ISSUE #2757: Replay crashes when stepping through trivial gtest targets
I've been experiencing a lot of crashes when trying to step through replays of gtest unit tests. I created a super-simple test which consistently reproduces the issue on my machine (running Fedora 32).

Any idea what's going on here?

## Reproduction Steps:

Create trivial gtest unit test:
```c++
// simple_test.cpp
#include <gtest/gtest.h>

TEST(simple_test, str_eq) {
    EXPECT_STREQ("abc", "abc");
}
```

Build test:
```
$ g++ -Wall -g -pthread simple_test.cpp -lgtest_main  -lgtest -lpthread -o simple_test
```

Record test:
```
$ rr record ./simple_test
rr: Saving execution to trace directory `/home/loganwendholt/.local/share/rr/simple_test-2'.
Running main() from /home/loganwendholt/googletest/googletest/src/gtest_main.cc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from simple_test
[ RUN      ] simple_test.str_eq
[       OK ] simple_test.str_eq (0 ms)
[----------] 1 test from simple_test (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (3 ms total)
[  PASSED  ] 1 test.
```

Replay test, create breakpoint at `main`, continue, then step once:
```
$ rr replay
GNU gdb (GDB) Fedora 9.1-3.fc32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/loganwendholt/.local/share/rr/simple_test-2/mmap_hardlink_3_simple_test...
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
Remote debugging using 127.0.0.1:2644
Reading symbols from /lib64/ld-linux-x86-64.so.2...
Reading symbols from /usr/lib/debug/usr/lib64/ld-2.31.so.debug...
0x00007faeb966d110 in _start () from /lib64/ld-linux-x86-64.so.2
(rr) b main
Breakpoint 1 at 0x406a2b
(rr) c
Continuing.

Breakpoint 1, 0x0000000000406a2b in main ()
(rr) s
Single stepping until exit from function main,
which has no line number information.
Running main() from /home/loganwendholt/googletest/googletest/src/gtest_main.cc
[FATAL /home/loganwendholt/Development/rr/src/ReplaySession.cc:482:cont_syscall_boundary()]
 (task 2645 (rec:2628) at time 281)
 -> Assertion `false' failed to hold. Replay got unrecorded signal {signo:SIGSEGV,errno:SUCCESS,code:SEGV_MAPERR,addr:0x7fae00007fae}
Tail of trace dump:
{
  real_time:352.804695 global_time:261, event:`PATCH_SYSCALL' tid:2628, ticks:356097
rax:0xca rbx:0x7faeb90fb6e0 rcx:0xffffffffffffffff rdx:0x7fffffff rsi:0x81 rdi:0x7faeb90ff028 rbp:0x7faeb90ff028 rsp:0x7ffde73eae80 r8:0x7faeb963a0a0 r9:0x1 r10:0x0 r11:0x246 r12:0x7ffde73eae80 r13:0x7ffde73eb1b8 r14:0x7faeb9661e48 r15:0x0 rip:0x7faeb962eaf5 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xffffffffffffffff fs_base:0x7faeb90f6740 gs_base:0x0
  { tid:2628, addr:0x7faeb969b05a, length:0x4f }
  { tid:2628, addr:0x7faeb962eaf5, length:0x5 }
  { tid:2628, addr:0x7faeb962eafa, length:0x3 }
}
{
  real_time:352.804811 global_time:262, event:`SYSCALL: gettid' (state:ENTERING_SYSCALL) tid:2628, ticks:356101
rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x0 rdi:0x0 rbp:0x7faeb90ff028 rsp:0x681ffd60 r8:0x0 r9:0x0 r10:0x0 r11:0x246 r12:0x7ffde73eae80 r13:0x7ffde73eb1b8 r14:0x7faeb9661e48 r15:0x0 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xba fs_base:0x7faeb90f6740 gs_base:0x0
}
{
  real_time:352.804848 global_time:263, event:`SYSCALL: gettid' (state:EXITING_SYSCALL) tid:2628, ticks:356101
rax:0xa44 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x0 rdi:0x0 rbp:0x7faeb90ff028 rsp:0x681ffd60 r8:0x0 r9:0x0 r10:0x0 r11:0x246 r12:0x7ffde73eae80 r13:0x7ffde73eb1b8 r14:0x7faeb9661e48 r15:0x0 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xba fs_base:0x7faeb90f6740 gs_base:0x0
}
{
  real_time:352.804973 global_time:264, event:`SYSCALL: perf_event_open' (state:ENTERING_SYSCALL) tid:2628, ticks:356101
rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0xffffffffffffffff rsi:0x0 rdi:0x681ffdb0 rbp:0x7faeb90ff028 rsp:0x681ffd60 r8:0x0 r9:0x0 r10:0xffffffffffffffff r11:0x246 r12:0x681ffdb0 r13:0xa44 r14:0x7faeb9661e48 r15:0x0 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x12a fs_base:0x7faeb90f6740 gs_base:0x0
}
{
  real_time:352.805036 global_time:265, event:`SYSCALL: perf_event_open' (state:EXITING_SYSCALL) tid:2628, ticks:356101
rax:0x3 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0xffffffffffffffff rsi:0x0 rdi:0x681ffdb0 rbp:0x7faeb90ff028 rsp:0x681ffd60 r8:0x0 r9:0x0 r10:0xffffffffffffffff r11:0x246 r12:0x681ffdb0 r13:0xa44 r14:0x7faeb9661e48 r15:0x0 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x12a fs_base:0x7faeb90f6740 gs_base:0x0
}
{
  real_time:352.805162 global_time:266, event:`SYSCALL: fcntl' (state:ENTERING_SYSCALL) tid:2628, ticks:356102
rax:0xffffffffffffffda rbx:0x3 rcx:0xffffffffffffffff rdx:0x64 rsi:0x406 rdi:0x3 rbp:0x3 rsp:0x681ffd00 r8:0x0 r9:0x0 r10:0x0 r11:0x246 r12:0x681ffdb0 r13:0xa44 r14:0x7faeb9661e48 r15:0x0 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x48 fs_base:0x7faeb90f6740 gs_base:0x0
}
{
  real_time:352.805208 global_time:267, event:`SYSCALL: fcntl' (state:EXITING_SYSCALL) tid:2628, ticks:356102
rax:0x64 rbx:0x3 rcx:0xffffffffffffffff rdx:0x64 rsi:0x406 rdi:0x3 rbp:0x3 rsp:0x681ffd00 r8:0x0 r9:0x0 r10:0x0 r11:0x246 r12:0x681ffdb0 r13:0xa44 r14:0x7faeb9661e48 r15:0x0 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x48 fs_base:0x7faeb90f6740 gs_base:0x0
  { tid:2628, addr:0x7faeb966226c, length:0x1 }
}
{
  real_time:352.805334 global_time:268, event:`SYSCALL: rrcall_init_buffers' (state:ENTERING_SYSCALL) tid:2628, ticks:356107
rax:0xffffffffffffffda rbx:0x3 rcx:0xffffffffffffffff rdx:0x0 rsi:0x0 rdi:0x681ffdb0 rbp:0x64 rsp:0x681ffd60 r8:0x0 r9:0x0 r10:0x0 r11:0x246 r12:0x681ffdb0 r13:0xa44 r14:0x64 r15:0x0 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x3e9 fs_base:0x7faeb90f6740 gs_base:0x0
}
{
  real_time:352.805773 global_time:269, event:`SYSCALL: rrcall_init_buffers' (state:EXITING_SYSCALL) tid:2628, ticks:356107
rax:0x7faeb8ff6000 rbx:0x3 rcx:0xffffffffffffffff rdx:0x0 rsi:0x0 rdi:0x681ffdb0 rbp:0x64 rsp:0x681ffd60 r8:0x0 r9:0x0 r10:0x0 r11:0x246 r12:0x681ffdb0 r13:0xa44 r14:0x64 r15:0x0 rip:0x70000005 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x3e9 fs_base:0x7faeb90f6740 gs_base:0x0
  { map_file:"<ZERO>", addr:0x7faeb8ff6000, length:0x100000, prot_flags:"rw-s", file_offset:0x0, device:33, inode:56779, data_file:"", data_offset:0x0, file_size:0x100000 }
  { tid:2628, addr:0x7faeb966226c, length:0x1 }
  { tid:2628, addr:0x7faeb96623b4, length:0x1 }
  { tid:2628, addr:0x681ffdb0, length:0x20 }
}
{
  real_time:352.806018 global_time:270, event:`SYSCALLBUF_FLUSH' tid:2628, ticks:375218
  { syscall:'futex', ret:0x0, size:0x14 }
  { syscall:'futex', ret:0x0, size:0x14 }
  { syscall:'futex', ret:0x0, size:0x14 }
}
{
  real_time:352.806079 global_time:271, event:`PATCH_SYSCALL' tid:2628, ticks:375218
rax:0x4f rbx:0x876030 rcx:0xffffffffffffffff rdx:0x7ffde73eadf1 rsi:0x1001 rdi:0x7ffde73e9df0 rbp:0x7ffde73e9df0 rsp:0x7ffde73e9ca0 r8:0x0 r9:0x7faeb92c5a40 r10:0xfffffffffffff27d r11:0x246 r12:0x7ffde73eaef0 r13:0x7ffde73eaf20 r14:0x1001 r15:0x7ffde73e9df0 rip:0x7faeb91f5060 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xffffffffffffffff fs_base:0x7faeb90f6740 gs_base:0x0
  { tid:2628, addr:0x7faeb969b0a9, length:0x4f }
  { tid:2628, addr:0x7faeb91f5060, length:0x5 }
  { tid:2628, addr:0x7faeb91f5065, length:0x3 }
}
{
  real_time:352.806087 global_time:272, event:`SYSCALLBUF_RESET' tid:2628, ticks:375218
}
{
  real_time:352.806185 global_time:273, event:`SYSCALL: getcwd' (state:ENTERING_SYSCALL) tid:2628, ticks:375224
rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x7ffde73eadf1 rsi:0x1001 rdi:0x7ffde73e9df0 rbp:0x4f rsp:0x681ffe20 r8:0x0 r9:0x7faeb92c5a40 r10:0xfffffffffffff27d r11:0x246 r12:0x7ffde73eaef0 r13:0x7ffde73eaf20 r14:0x1001 r15:0x7ffde73e9df0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x4f fs_base:0x7faeb90f6740 gs_base:0x0
}
{
  real_time:352.806231 global_time:274, event:`SYSCALL: getcwd' (state:EXITING_SYSCALL) tid:2628, ticks:375224
rax:0x14 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x7ffde73eadf1 rsi:0x1001 rdi:0x7ffde73e9df0 rbp:0x4f rsp:0x681ffe20 r8:0x0 r9:0x7faeb92c5a40 r10:0xfffffffffffff27d r11:0x246 r12:0x7ffde73eaef0 r13:0x7ffde73eaf20 r14:0x1001 r15:0x7ffde73e9df0 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x4f fs_base:0x7faeb90f6740 gs_base:0x0
  { tid:2628, addr:0x7ffde73e9df0, length:0x14 }
}
{
  real_time:352.806657 global_time:275, event:`PATCH_SYSCALL' tid:2628, ticks:410785
rax:0x5 rbx:0x7faeb92c7300 rcx:0xffffffffffffffff rdx:0x7ffde73ea920 rsi:0x7ffde73ea920 rdi:0x1 rbp:0x7faeb92c6500 rsp:0x7ffde73ea918 r8:0x1 r9:0x8 r10:0x44c44c r11:0x246 r12:0x44c44c r13:0x7faeb92c7300 r14:0x14 r15:0x0 rip:0x7faeb91f3a77 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xffffffffffffffff fs_base:0x7faeb90f6740 gs_base:0x0
  { tid:2628, addr:0x7faeb969b0f8, length:0x4f }
  { tid:2628, addr:0x7faeb91f3a77, length:0x5 }
  { tid:2628, addr:0x7faeb91f3a7c, length:0x3 }
}
{
  real_time:352.806809 global_time:276, event:`SYSCALLBUF_FLUSH' tid:2628, ticks:411272
  { syscall:'fstat', ret:0x0, size:0xa0 }
}
{
  real_time:352.806871 global_time:277, event:`PATCH_SYSCALL' tid:2628, ticks:411272
rax:0x1 rbx:0x50 rcx:0xffffffffffffffff rdx:0x50 rsi:0x876b30 rdi:0x1 rbp:0x876b30 rsp:0x7ffde73ea998 r8:0xffffffff r9:0x4f r10:0x44c410 r11:0x246 r12:0x50 r13:0x7faeb92c6500 r14:0x50 r15:0x7faeb92c6700 rip:0x7faeb91f45e5 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xffffffffffffffff fs_base:0x7faeb90f6740 gs_base:0x0
  { tid:2628, addr:0x7faeb969b147, length:0x4f }
  { tid:2628, addr:0x7faeb91f45e5, length:0x5 }
  { tid:2628, addr:0x7faeb91f45ea, length:0x3 }
}
{
  real_time:352.806879 global_time:278, event:`SYSCALLBUF_RESET' tid:2628, ticks:411272
}
{
  real_time:352.806976 global_time:279, event:`SYSCALL: write' (state:ENTERING_SYSCALL) tid:2628, ticks:411284
rax:0xffffffffffffffda rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x50 rsi:0x876b30 rdi:0x1 rbp:0x1 rsp:0x681ffe20 r8:0xffffffff r9:0x4f r10:0x44c410 r11:0x246 r12:0x0 r13:0x7faeb92c6500 r14:0x876b30 r15:0x50 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x1 fs_base:0x7faeb90f6740 gs_base:0x0
}
{
  real_time:352.807137 global_time:280, event:`SYSCALL: write' (state:EXITING_SYSCALL) tid:2628, ticks:411284
rax:0x50 rbx:0x681fffa0 rcx:0xffffffffffffffff rdx:0x50 rsi:0x876b30 rdi:0x1 rbp:0x1 rsp:0x681ffe20 r8:0xffffffff r9:0x4f r10:0x44c410 r11:0x246 r12:0x0 r13:0x7faeb92c6500 r14:0x876b30 r15:0x50 rip:0x70000002 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0x1 fs_base:0x7faeb90f6740 gs_base:0x0
}
{
  real_time:352.807389 global_time:281, event:`PATCH_SYSCALL' tid:2628, ticks:413902
rax:0xe4 rbx:0x0 rcx:0xffffffffffffffff rdx:0x0 rsi:0x7ffde73eae40 rdi:0x0 rbp:0x0 rsp:0x7ffde73eae18 r8:0x7ffde73eae00 r9:0x7ffde73eace0 r10:0x7faeb968a7b0 r11:0x246 r12:0x7ffde73eae40 r13:0x0 r14:0x0 r15:0x0 rip:0x7ffde73fb9d5 eflags:0x246 cs:0x33 ss:0x2b ds:0x0 es:0x0 fs:0x0 gs:0x0 orig_rax:0xffffffffffffffff fs_base:0x7faeb90f6740 gs_base:0x0
  { map_file:"<ZERO>", addr:0x7ffde73fe000, length:0x1000, prot_flags:"r-xp", file_offset:0x0, device:0, inode:0, data_file:"", data_offset:0x0, file_size:0x1000 }
  { tid:2628, addr:0x7ffde73fe000, length:0x4f }
  { tid:2628, addr:0x7ffde73fb9d5, length:0x5 }
  { tid:2628, addr:0x7ffde73fb9da, length:(nil) }
}
{
  real_time:352.807496 global_time:282, event:`SYSCALLBUF_FLUSH' tid:2628, ticks:414641
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
  { syscall:'clock_gettime', ret:0x0, size:0x20 }
}
=== Start rr backtrace:
rr(_ZN2rr13dump_rr_stackEv+0x33)[0x8eebab]
rr(_ZN2rr9GdbServer15emergency_debugEPNS_4TaskE+0x168)[0x7521fc]
rr[0x780b23]
rr(_ZN2rr21EmergencyDebugOstreamD1Ev+0x5a)[0x780d0a]
rr(_ZN2rr13ReplaySession21cont_syscall_boundaryEPNS_10ReplayTaskERKNS0_15StepConstraintsE+0x1d4)[0x84f78c]
rr(_ZN2rr13ReplaySession18patch_next_syscallEPNS_10ReplayTaskERKNS0_15StepConstraintsEb+0x58)[0x8537b8]
rr(_ZN2rr13ReplaySession18try_one_trace_stepEPNS_10ReplayTaskERKNS0_15StepConstraintsE+0x1a7)[0x853eb5]
rr(_ZN2rr13ReplaySession11replay_stepERKNS0_15StepConstraintsE+0x160)[0x855102]
rr(_ZN2rr14ReplayTimeline19replay_step_forwardENS_10RunCommandEl+0xf1)[0x86f057]
rr(_ZN2rr9GdbServer14debug_one_stepERNS_10GdbRequestE+0x571)[0x74f941]
rr(_ZN2rr9GdbServer12serve_replayERKNS0_15ConnectionFlagsE+0x4c3)[0x751507]
rr[0x84bb24]
rr(_ZN2rr13ReplayCommand3runERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x3ba)[0x84c45c]
rr(main+0x20c)[0x908c08]
/lib64/libc.so.6(__libc_start_main+0xf2)[0x7f0a92f67042]
rr(_start+0x2e)[0x6bd6be]
=== End rr backtrace
Launch gdb with
  gdb '-l' '10000' '-ex' 'set sysroot /' '-ex' 'target extended-remote 127.0.0.1:2645' /home/loganwendholt/.local/share/rr/simple_test-2/mmap_hardlink_3_simple_test

### PR DESCRIPTION
**Pull request by khuey**
_dl_runtime_resolve has a weird stack frame (because of how the PLT trampolines into it). When the function is entered the return address is *not* at %rsp. The dynamic linker has CFI directives to tell a debugger what's going on, but if we jump out of the binary into our patch code there's no clue for gdb what's going on. Gdb decides that whatever's at %rsp must be the return address (per the normal x86-64 ABI at function entry) and writes a breakpoint there. But that location is actually pointing to data associated with the PLT! Bad things ensue.

Fixes #2757

### CODE REVIEW

**Comment by khuey** [comment]
@loganwendholt can you give this a try?

@Keno I'd appreciate another set of eyes on this because it's scary code, and roc is on vacation.

**Comment by Keno** [comment]
I'm a little worried about modifying the stack before our stack switching code. Does `_dl_runtime_resolve` modify the stack already or does it observe the ABI redzone?

**Comment by loganwendholt** [comment]
Looks like this does get rid of the crash for me. 

Here's the simple gtest:

```
$ ./rr replay
GNU gdb (GDB) Fedora 9.1-3.fc32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/loganwendholt/.local/share/rr/simple_test-14/mmap_hardlink_3_simple_test...
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
Remote debugging using 127.0.0.1:40662
Reading symbols from /lib64/ld-linux-x86-64.so.2...
Reading symbols from /usr/lib/debug/usr/lib64/ld-2.31.so.debug...
0x00007f7fab247110 in _start () from /lib64/ld-linux-x86-64.so.2
(rr) b main
Breakpoint 1 at 0x406a2b
(rr) c
Continuing.

Breakpoint 1, 0x0000000000406a2b in main ()
(rr) s
Single stepping until exit from function main,
which has no line number information.
Running main() from /home/loganwendholt/googletest/googletest/src/gtest_main.cc
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from simple_test
[ RUN      ] simple_test.str_eq
[       OK ] simple_test.str_eq (0 ms)
[----------] 1 test from simple_test (1 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (2 ms total)
[  PASSED  ] 1 test.

Program received signal SIGKILL, Killed.
0x0000000070000002 in syscall_traced () from /home/loganwendholt/khuey/build/lib/rr/librrpage.so
(rr) s
Single stepping until exit from function syscall_traced,
which has no line number information.
[Inferior 1 (process 171728) exited normally]
```

and the minimal hello_world:
```[loganwendholt@localhost bin]$ ./rr record ~/minimal
rr: Saving execution to trace directory `/home/loganwendholt/.local/share/rr/minimal-3'.
hello world
[loganwendholt@localhost bin]$ ./rr replay
GNU gdb (GDB) Fedora 9.1-3.fc32
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/loganwendholt/.local/share/rr/minimal-3/mmap_hardlink_3_minimal...
(No debugging symbols found in /home/loganwendholt/.local/share/rr/minimal-3/mmap_hardlink_3_minimal)
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
Remote debugging using 127.0.0.1:40786
Reading symbols from /lib64/ld-linux-x86-64.so.2...
Reading symbols from /usr/lib/debug/usr/lib64/ld-2.31.so.debug...
0x00007f9ebc36f110 in _start () from /lib64/ld-linux-x86-64.so.2
(rr) b main
Breakpoint 1 at 0x40113a
(rr) c
Continuing.

Breakpoint 1, 0x000000000040113a in main ()
(rr) s
Single stepping until exit from function main,
which has no line number information.
hello world

Program received signal SIGKILL, Killed.
0x0000000070000002 in syscall_traced () from /home/loganwendholt/khuey/build/lib/rr/librrpage.so
(rr) s
Single stepping until exit from function syscall_traced,
which has no line number information.
[Inferior 1 (process 171851) exited normally]
(rr) 
```

**Comment by khuey** [comment]
What do you mean by this? This isn't on the syscall path (afaik).

**Comment by Keno** [comment]
Ah, you're right. I guess we don't do any stack switching here. I also looked at the glibc implementation and it doesn't observe any ABI redzones, so that's not a concern. LGTM in that case then. I guess we would probably also just have enough bytes to just jump to a known address in the rr page, which we could then give proper CFI info, but this seems fine to me also.

**Review by Keno — APPROVED** [review]

**Comment by khuey** [comment]
Going to the rr page to give real CFI is a good idea (and only possible thanks to your stuff from last week, ha) but I don't see how we can get there (loading an absolute address into r11 and then doing an indirect jump through r11 would be 9 bytes and we only have 8).  What did you have in mind?

**Comment by Keno** [comment]
The rr page is in the low 4GB, so I thought we had enough space. If not, can't we expand the size of the patch? I didn't think the function had any interfering instructions?

**Comment by khuey** [comment]
The next instruction varies between the various _dl_runtime_resolve functions so taking any additional space would be annoying.

I believe using the extended jump stuff to get to the rr page would trigger the same gdb misbehavior that we're trying to avoid, so we'd need to get out of the dynamic linker binary and into the rr page in a single go.

The rr page is in the low 4GB but loading a 4 byte value into r11 takes 6 bytes, and then there's another 3 for the indirect jump. If we could use a register that doesn't require REX.R I suppose we could get that down to 5 and 2 respectively which would fit. But there's also the problem of the dynamic linker's CFI, and any patch we'd do here that executes more than one instruction would almost certainly run afoul of the reality the CFI tells gdb to expect.

I'm going to land this as is but if you come up with a solution I'm all ears :)

**Pull request merged**
