### PR TITLE
Fix madvise fracture during replay

### PR DESCRIPTION
**Pull request by Keno**
This is an incomplete PR, because although the test case passes as included (with replay -a), it does not pass when running from the debugger prompt. I do not know what the difference between the two scenarios is. rr's logs are identical, there are no spurious debugger traps or anything. I did trace the kernel and there is a minor difference, but it is not particularly helpful. Anyway, I'll look at this some more, but if anybody has bright ideas what difference running with GDB attached vs not makes, I'm all ears.

The core issue I'm trying to fix here is the following, when replaying the included test case, which emulates some (questionably sound) asan behavior:
```
[FATAL src/AutoRemoteSyscalls.cc:734:check_syscall_result()] 
 (task 1144611 (rec:1088200) at time 1206)
 -> Assertion `false' failed to hold. Syscall mmap failed with errno ENOMEM
Tail of trace dump:
```
What happens is that the program exceeds the total number of allowed mappings, because the kernel refuses to coalesce the mappings back after the second madvise, for unknown reasons. The coalescing does happen without rr, during record, as well as during `replay -a`. At first I thought this was a syscallbuf vs non-syscallbuf behavior difference, and indeed I believe that was a problem as well (which is fixed in this PR), but the mentioned behavior persists even with this patch applied.

I'll look at this some more, but I'm somewhat stumped.

<details><summary>Kernel function tracing results</summary>

Good:
```
15)               |  do_syscall_64() {
15)               |    __x64_sys_madvise() {
15)               |      down_write_killable() {
15)               |        _cond_resched() {
15)   0.210 us    |          rcu_all_qs();
15)   0.620 us    |        }
15)   1.020 us    |      }
15)               |      find_vma_prev() {
15)               |        find_vma() {
15)   0.280 us    |          vmacache_find();
15)   0.230 us    |          vmacache_update();
15)   1.540 us    |        }
15)   1.930 us    |      }
15)   0.230 us    |      blk_start_plug();
15)               |      hugepage_madvise() {
15)               |        khugepaged_enter_vma_merge() {
15)   0.240 us    |          hugepage_vma_check();
15)   0.790 us    |        }
15)   1.370 us    |      }
15)   0.370 us    |      vma_merge();
15)               |      blk_finish_plug() {
15)   0.250 us    |        blk_flush_plug_list();
15)   0.820 us    |      }
15)   0.200 us    |      up_write();
15)   8.150 us    |    }
15)   0.210 us    |    fpregs_assert_state_consistent();
15)   9.280 us    |  }
15)               |  do_syscall_64() {
15)               |    __x64_sys_madvise() {
15)               |      down_write_killable() {
15)               |        _cond_resched() {
15)   0.210 us    |          rcu_all_qs();
15)   0.610 us    |        }
15)   1.010 us    |      }
15)               |      find_vma_prev() {
15)               |        find_vma() {
15)   0.240 us    |          vmacache_find();
15)   0.630 us    |        }
15)   1.020 us    |      }
15)   0.230 us    |      blk_start_plug();
15)               |      vma_merge() {
15)   0.260 us    |        can_vma_merge_before.part.0();
15)               |        __vma_adjust() {
15)   0.250 us    |          vma_adjust_trans_huge();
15)   0.460 us    |          __vma_rb_erase();
15)               |          vm_area_free() {
15)   0.360 us    |            kmem_cache_free();
15)   0.790 us    |          }
15)   3.150 us    |        }
15)               |        khugepaged_enter_vma_merge() {
15)   0.230 us    |          hugepage_vma_check();
15)   0.620 us    |        }
15)   4.930 us    |      }
15)               |      blk_finish_plug() {
15)   0.230 us    |        blk_flush_plug_list();
15)   0.650 us    |      }
15)   0.210 us    |      up_write();
15)   9.500 us    |    }
15)   0.200 us    |    fpregs_assert_state_consistent();
15) + 10.330 us   |  }
```
Bad:
```
15)               |  do_syscall_64() {
15)               |    __x64_sys_madvise() {
15)               |      down_write_killable() {
15)               |        _cond_resched() {
15)   0.210 us    |          rcu_all_qs();
15)   0.660 us    |        }
15)   1.070 us    |      }
15)               |      find_vma_prev() {
15)               |        find_vma() {
15)   0.300 us    |          vmacache_find();
15)   0.280 us    |          vmacache_update();
15)   1.340 us    |        }
15)   1.730 us    |      }
15)   0.240 us    |      blk_start_plug();
15)               |      hugepage_madvise() {
15)               |        khugepaged_enter_vma_merge() {
15)               |          hugepage_vma_check() {
15)   0.230 us    |            is_vma_temporary_stack();
15)   0.790 us    |          }
15)   1.400 us    |        }
15)   1.980 us    |      }
15)   0.360 us    |      vma_merge();
15)               |      blk_finish_plug() {
15)   0.250 us    |        blk_flush_plug_list();
15)   0.730 us    |      }
15)   0.220 us    |      up_write();
15)   8.530 us    |    }
15)   0.210 us    |    fpregs_assert_state_consistent();
15) + 10.050 us   |  }
15)               |  do_syscall_64() {
15)               |    __x64_sys_madvise() {
15)               |      down_write_killable() {
15)               |        _cond_resched() {
15)   0.210 us    |          rcu_all_qs();
15)   0.620 us    |        }
15)   1.040 us    |      }
15)               |      find_vma_prev() {
15)               |        find_vma() {
15)   0.240 us    |          vmacache_find();
15)   0.630 us    |        }
15)   1.010 us    |      }
15)   0.220 us    |      blk_start_plug();
15)               |      vma_merge() {
15)   0.230 us    |        can_vma_merge_before.part.0();
15)   0.710 us    |      }
15)               |      blk_finish_plug() {
15)   0.240 us    |        blk_flush_plug_list();
15)   0.650 us    |      }
15)   0.210 us    |      up_write();
15)   5.320 us    |    }
15)   0.200 us    |    fpregs_assert_state_consistent();
15)   6.140 us    |  }
```
</details>

### CODE REVIEW

**Comment by Keno** [comment]
Hmm, I wonder if the difference is that without `-a`, we create checkpoints along the way, so some of the mappings are potentially COW-shared. Does that prevent coalescing?

**Comment by Keno** [comment]
> Hmm, I wonder if the difference is that without `-a`, we create checkpoints along the way, so some of the mappings are potentially COW-shared. Does that prevent coalescing?

Hmm, so after reading https://lwn.net/Articles/383162/, it does appear that indeed forking would prevent coalescing of post-fork mappings with pre-fork mappings that are still live in the forked child. Though that doesn't explain why the post-fork mappings don't coalesce into one big block at the start, so that's an outstanding question still.

**Comment by Keno** [comment]
Alright, updates. I can no longer reproduce the `replay -a` vs `replay` difference in the test case. I may have been doing something dumb there, but regardless, I've updated the commit to fix the particular  issue of inconsistent madvise flags between the syscallbuf and the rr path. Unfortunately, I may have misdiagnosed the original asan failure, as even with this patch, replay thereof still fails (though suceeds in `-a` mode). I do however believe that the `anon_vma` issue linked above adequately explains that. If we fork a vma, it is no longer eligible for coalescing with adjacent vmas, so for a bigger long-running program like my asan test case, the fracturing can become quite significant. I'll be submitting a patch to asan to address this issue also. Nevertheless, this PR still addresses a real issue (if not the one I actually cared about) and should hopefully be good to go now.

**Comment by Keno** [comment]
Asan patch is at https://reviews.llvm.org/D131321.

**Comment by rocallahan** [comment]
Relevant tests failed:
```
	314 - madvise_fracture_flags (Failed)
	315 - madvise_fracture_flags-no-syscallbuf (Failed)
	1025 - madvise_dontfork-no-syscallbuf (Failed)
	1730 - madvise_fracture_flags-32 (Failed)
	1731 - madvise_fracture_flags-32-no-syscallbuf (Failed)
	2441 - madvise_dontfork-32-no-syscallbuf (Failed)
```

**Comment by Keno** [comment]
Yep, I'm working on it. I think `madvise_dontfork` is actually just a different prexisting bug. Fix incoming.

**Comment by Keno** [comment]
Should be fixed. Let's see what CI says.

**Pull request merged**
