### PR TITLE
Make breakpoint.run test run against LLDB as well as GDB

### PR DESCRIPTION
**Pull request by rocallahan**
Test PR to see if CI works

### CODE REVIEW

**Comment by rocallahan** [comment]
@Keno looks like we need to change the CI config to install an LLDB package. Do you know of anyone who can do that for us? Thanks!

**Comment by Keno** [comment]
@staticfloat or @DilumAluthge can we get an LLDB package installed in the CI base image?

**Comment by DilumAluthge** [comment]
Yep, should be easy enough.

**Comment by DilumAluthge** [comment]
What's the minimum version of lldb that would work?

**Comment by rocallahan** [comment]
Any relatively new version should be fine. The latest version that's
convenient

**Comment by DilumAluthge** [comment]
Alright, this should do the trick: https://github.com/rr-debugger/rr/pull/3691

**Pull request merged**
