### PR TITLE
add support for XFS quotactl(Q_XGETQSTAT...

### LINKED ISSUE #2013: Assertion while recording `ret == -ENOENT || ret == -ENODEV || ret == -ENOTBLK || ret == -EINVAL' failed to hold.  unknown quotactl(0x5805)
Me again unfortunately with another smbd issue. Recording fails with this assertion failure (using latest git 1022e348 ):

    [FATAL /home/aaptel/prog/rr/rr.git/src/record_syscall.cc:5009:rec_process_syscall_arch() errno: SUCCESS] 
     (task 28255 (rec:28255) at time 61003)
     -> Assertion `ret == -ENOENT || ret == -ENODEV || ret == -ENOTBLK || ret == -EINVAL' failed to hold.  unknown quotactl(0x5805)
    Launch gdb with
      gdb '-l' '10000' '-ex' 'target extended-remote :28255' /tmp/smb/sbin/smbd

Steps to reproduce:

    git clone git://git.samba.org/samba.git samba
    cd samba
    ./buildtools/bin/waf configure -C -j8 \
                                        --disable-cups --enable-selftest --with-libarchive  \
                                        --enable-debug --picky-developer \
                                        --enable-developer \
                                        --bundled-libraries=ALL \
                                        --prefix=/tmp/smb/ \
                                        --localstatedir=/tmp/smbstate
    ./buildtools/bin/waf build -j8
    ./buildtools/bin/waf install
    rm -rf /tmp/share
    mkdir -p /tmp/share
    chmod 777 /tmp/share
    cat <<EOF > /tmp/smb/etc/smb.conf
    [global]
    logging = ringbuf
    log level = 0
     
    [share]
    path = /tmp/share
    read only = no
    guest ok = yes
    EOF
    for i in $(seq 100 9000); do
        echo ABC${i}DEF > /tmp/share/${i}xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    done

as root:

    rr record /tmp/smb/sbin/smbd -i

in other shell:

    /tmp/smb/bin/smbclient //localhost/share -U% -c ls

### PR DESCRIPTION
**Pull request by aaptel**
fixes #2013 

thanks to @khuey for the hints

### CODE REVIEW

**Comment by aaptel** [comment]
the header is provided by the xfsprogs-devel package on my system (openSUSE)

**Comment by rocallahan** [comment]
How about `#include <linux/dqblk_xfs.h>` instead?

**Comment by rocallahan** [comment]
If that doesn't work then probably we should just define the required symbols in kernel_supplement.h and rrutil.h rather than require everyone who builds rr to install an extra package.

**Comment by GitMensch** [comment]
> How about `#include <linux/dqblk_xfs.h>` instead?
> 
> If that doesn't work then probably we should just define the required symbols in kernel_supplement.h and rrutil.h rather than require everyone who builds rr to install an extra package.

The header was included and it seems to work, but that wasn't integrated (rechecked: the header is still not used in the current source). The issue behind this PR is still open, too; so: would there be a reason to not pull it in?

**Comment by rocallahan** [comment]
I'm just going to close this for now.

**Comment by GitMensch** [comment]
> I'm just going to close this for now.

Wouldn't it be reasonable to either close the root issue - where @khuey asked @aaptel to do this PR, which was adjusted as you've asked, too? Or possibly keep both open, or close the issue by pulling this in?

**Pull request closed without merging**
