### PR TITLE
wrap rr macros restart and jump in python

### LINKED ISSUE #3859: Spurious "Really redefine built-in command" logged on screen
Not a bug, but it's mildly annoying.

Currently, when rr starts, these lines are logged

```
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
Really redefine built-in command "jump"? (y or n) [answered Y; input not from terminal]
```

that's annoying.

It's possible to delete them by setting `set confirm off` before the redefinitions and `set confirm on` afterwards, but then user might be confused if they put `set confirm off` themselves.

Relevant code: https://github.com/rr-debugger/rr/blob/master/src/launch_debugger.cc#L51

A better way may be to use Python:

```
python gdb.execute('''define restart\nrun c$arg0\nend''')
```

Somehow, that suppresses the message.

(we're already using Python later anyway, so it doesn't seem to be an issue.)

### PR DESCRIPTION
**Pull request by GitMensch**
fixes #3859 warnings during startup

### CODE REVIEW

**Comment by GitMensch** [comment]
Looks like it is working - CI fails with an unrelated error during build:

~~~
/tmp/actions-runner/_work/rr/rr/src/test/open_null.c: In function ‘main’:
/tmp/actions-runner/_work/rr/rr/src/test/open_null.c:8:20: error: ‘SYS_open’ undeclared (first use in this function); did you mean ‘SYS_fsopen’?
    8 |   int fd = syscall(SYS_open, NULL, O_RDONLY);
      |                    ^~~~~~~~
      |                    SYS_fsopen
/tmp/actions-runner/_work/rr/rr/src/test/open_null.c:8:20: note: each undeclared identifier is reported only once for each function it appears in
~~~

**Comment by GitMensch** [comment]
Can you please give some details on the failure? "Doesn't work" is hardly something I can work with :-/

**Comment by user202729** [comment]
I think the problem is you're having `\n` in C++ code, which passes the literal newline to gdb, which of course will break because then the `python` command will just be the first line.

Replace `\n` with `\\n` might work (or split the whole thing to multiple lines and use triple-quote, see e.g. the Python block below), but I haven't tested locally.

**Comment by sidkshatriya** [comment]
> Can you please give some details on the failure? "Doesn't work" is hardly something I can work with :-/

Sorry -- I didn't have time to debug the issue. I simply reverted the commit and saw the tests working again. Are you able to run the test `checkpoint_mmap_shared` on your local machine ? If the test fails for you also I think you will be able to debug the error.

**Comment by sidkshatriya** [comment]
@user202729 
> (On another note, does GitHub Actions not run on Fedora?)

Looking at the "Details" button where this commit was merged it does not seem the CI tests were run at all. 

@GitMensch 
Here is the error taken from the gdb log
```
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /tmp/rr-test-checkpoint_mmap_shared-VbXYvN2mk/mmap_shared-VbXYvN2mk-0/mmap_hardlink_3_mmap_shared-VbXYvN2mk..
  File "<string>", line 1
    gdb.execute('define jump
                ^
SyntaxError: unterminated string literal (detected at line 1)
/proc/4133/fd/5:180: Error in sourced command file:
Error occurred in Python: unterminated string literal (detected at line 1) (<string>, line 1)
...
...
```

**Comment by GitMensch** [comment]
Ah, yes, that makes sense: executing `python gdb.execute('define restart\nrun c$arg0\nend')` in GDB works fine - but we need to escape the \\n for the C++ literal. I'm working on that now.

**Comment by sidkshatriya** [comment]
@user202729 was correct in their analysis. The following diff causes the test to pass again.

```diff
--- a/src/launch_debugger.cc
+++ b/src/launch_debugger.cc
@@ -50,8 +50,8 @@ static const string& gdb_rr_macros() {
     ss << DebuggerExtensionCommandHandler::gdb_macros()
        // gdb warns about redefining inbuilt commands, silence that by
        // wrapping it in python code
-       << "python gdb.execute('define jump\nrr-denied jump\nend')"
-       << "python gdb.execute('define restart\nrun c$arg0\nend')"
+       << "python gdb.execute('define jump\\nrr-denied jump\\nend')\n"
+       << "python gdb.execute('define restart\\nrun c$arg0\\nend')\n"
        << "document restart\n"
        << "restart at checkpoint N\n"
        << "checkpoints are created with the 'checkpoint' command\n"
```

**Comment by sidkshatriya** [comment]
@GitMensch The commit that you added to https://github.com/GitMensch/rr/commit/9f7c2fc933a83648274ef84148c16406f9e217dd will **not** work as you need a `\n` at the end of the C++ string. Please see the diff that I posted above.

**Comment by GitMensch** [comment]
Should be fixed with #3869 ... which in the end ended with exactly the diff from above.

**Pull request merged**
