### PR TITLE
aarch64: Save/Restore PAC keys

### LINKED ISSUE #3568: aarch64: rr crashes immediately upon replay -e
On Fedora 38 aarch64 (Apple Silicon), this can be reproduced with:
```
[benwibking@fedora ~]$ rr_install/bin/rr record echo "Hello, world"
rr: Saving execution to trace directory `/home/benwibking/.local/share/rr/echo-2'.
Hello, world
[benwibking@fedora ~]$ rr_install/bin/rr replay -e
[ERROR src/Registers.cc:299:maybe_print_reg_mismatch()] x[30] 0x41ffffb0998d40 != 0x7cffffb0998d40 (replaying vs. recorded)
[FATAL src/Registers.cc:409:compare_register_files()] 
 (task 24832 (rec:24825) at time 7)
 -> Assertion `!bail_error || match' failed to hold. Fatal register mismatch (ticks/rec:2748/2748)
Tail of trace dump:
=== Start rr backtrace:
rr_install/bin/rr(_ZN2rr9GdbServer15emergency_debugEPNS_4TaskE+0xe0)[0x48b320]
rr_install/bin/rr[0x49cc1c]
rr_install/bin/rr[0x49d81c]
rr_install/bin/rr(_ZN2rr9Registers22compare_register_filesEPNS_10ReplayTaskEPKcRKS0_S4_S6_NS_16MismatchBehaviorE+0x90)[0x518584]
rr_install/bin/rr(_ZN2rr10ReplayTask13validate_regsEj+0x164)[0x52dc04]
rr_install/bin/rr(_ZN2rr13ReplaySession13enter_syscallEPNS_10ReplayTaskERKNS0_15StepConstraintsE+0x2b4)[0x51f504]
rr_install/bin/rr(_ZN2rr13ReplaySession11replay_stepERKNS0_15StepConstraintsE+0x104)[0x522c04]
rr_install/bin/rr(_ZN2rr14ReplayTimeline19replay_step_forwardENS_10RunCommandE+0x84)[0x53b748]
rr_install/bin/rr(_ZN2rr9GdbServer12serve_replayERKNS0_15ConnectionFlagsE+0x70)[0x486e00]
rr_install/bin/rr[0x5193a4]
rr_install/bin/rr(_ZN2rr13ReplayCommand3runERSt6vectorINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESaIS7_EE+0x444)[0x519d64]
rr_install/bin/rr(main+0x168)[0x433998]
/lib64/libc.so.6(+0x30598)[0xffffb6730598]
/lib64/libc.so.6(__libc_start_main+0x9c)[0xffffb6730670]
rr_install/bin/rr(_start+0x30)[0x434f30]
=== End rr backtrace
Launch gdb with
  gdb '-l' '10000' '-ex' 'set sysroot /' '-ex' 'target extended-remote 127.0.0.1:24832' /home/benwibking/.local/share/rr/echo-2/mmap_clone_5_echo
```

### PR DESCRIPTION
**Pull request by Keno**
Should fix #3568.

### CODE REVIEW

**Comment by Keno** [comment]
We'll look into getting a buildkite agent set up on an M1, so we can actually test this.

**Comment by Keno** [comment]
Seeing the following test failures on an M1 with Fedora Asahi Remix:
```
        1128 - vdso_clock_gettime_stack (Failed)
        1132 - vdso_time_stack (Failed)
        1230 - fork_exec_info_thr (Failed)
        1231 - fork_exec_info_thr-no-syscallbuf (Failed)
        1260 - record_replay (Failed)
        1261 - record_replay-no-syscallbuf (Failed)
        1266 - replay_serve_files (Failed)
        1267 - replay_serve_files-no-syscallbuf (Failed)
        1346 - vfork_done_clone (Failed)
        1347 - vfork_done_clone-no-syscallbuf (Failed)
```

**Comment by Keno** [comment]
I guess to fix `record_replay`, I should add ptrace emulation support for these regsets.

**Comment by GitMensch** [comment]
From the testing that Ben did `re replay` chrashes without and works with this PR included - is there anything that needs to be done now or can this be pulled in and follow-up PRs be created for things that are considered to be missing?

**Comment by GitMensch** [comment]
Friendly ping @Keno to possibly merge as is (existing tests that failed before on aarch64 now pass) and add follow-up PRs if/as necessary.

**Comment by Keno** [comment]
I was hoping to get the M1 buildkite up, so we can actually test this. Let me follow up on that.

**Comment by BenWibking** [comment]
@Keno Just wanted to ping about this. Is the testing infrastructure in place for this now?

**Comment by pcc** [comment]
Ping; this also fixed my PAC issue.

Note that in addition to the keys themselves, we'll also need to save/restore the key enabled state, which is available via `REGSET_PAC_ENABLED_KEYS`.

**Comment by jvoisin** [comment]
Yup, fixing things here as well :)

**Comment by eggyal** [comment]
Is there anything that the community can do to help move this forward?

**Comment by pcc** [comment]
There are a few known missing aspects of PAC support that I'm aware of:
- ptrace emulation (needed for rr to run under itself)
- PR_PAC_SET_ENABLED_KEYS support
- Support for detecting attempts to replay on incompatible systems. For example, FEAT_FPAC controls the semantics of the AUT* instructions, so a trace captured on a machine without FEAT_FPAC cannot be replayed on a machine with FEAT_FPAC and vice versa. There are also several incompatible signing schemes that would prevent replay on a system that implements a different one (I know of at least 3: two standardized ones and a non-standard one that Apple CPUs implement).

But these are fairly minor features: for 99+% of users who record and replay on the same system, rr will work fine. And if replay fails due to missing PAC support, it will not be obvious what the issue is unless you already know about PAC. So I think this should land as is, and the remaining features can be added in followup changes and the CI support can be added asynchronously. Since there's no PAC support in CI, at worst we introduce a bug that breaks PAC and then we're in the same position as if this patch didn't land.

**Comment by rocallahan** [comment]
I merged this with a small tweak to fix the non-ARM builds.

Please file issues for the followup work. Thanks!

**Pull request closed without merging**
