### PR TITLE
Put the rr page into a proper ELF library

### LINKED ISSUE #2721: Give rr page proper unwind info
I'm seeing occasional failures in the Julia backtracing tests when running under rr which happen whenever the thread whose backtrace is being taken happens to be in the rr page. The reason for the failure is that our backtracing relies on the CFA info for unwinding (rather than the more heuristic unwinder that gdb has for example). However, the rr page does not have any unwind info, since it's not technically part of any shared library. I can hack around this by just adding an rr special case in julia's unwinder, but I figured if we ran into it others might as well, so perhaps there is a general solution on the rr side. One option is certainly `__register_frame` which is provided by the unwind library to dynamically register (e.g. JITTed) frames. However, I'm worried that mechanism would be a bit brittle since it requires the unwind library to be listening for these events (and in particular requires the unwind to be done using the system unwind library if that unwind library is the one set up to listen for such events). I think a more robust scheme would actually be to try to make the rr page part of some dynamic library that the dynamic linker knows about (since all unwind libraries know how to read the dynamic linker maps). I think a scheme that would work is:

1. Make the rr_page an ET_EXEC elf file rather than a plain binary (with an appropriate PT_LOAD to load it at the right absolute address)
2. Link librrpreload with rr_page (in the DT_NEEDED sense)
3. When the dynamic linker tries to execute the PT_LOAD command by mapping over the RR page, recognize that it is the rr page being mapped and don't clear the IS_RR_PAGE flag.

That way we can add an eh_frame section to the rr page ET_EXEC file that the dynamic linker would know about and could be accessed by any unwind library.

Thoughts? If that seems too complicated for a marginal case, I'm happy to just hack around it on our side.

### PR DESCRIPTION
**Pull request by Keno**
This fixes #2721, though the strategy I proposed there doesn't
quite work as stated, so this is slightly different.

To recap:
We are seeing some test failures under rr, because our runtime
system assumes that it can asynchronously unwind from anywhere
(basically having things built with -fasynchronous-unwind-tables
and proper CFI for assembly code). However, this ran into problems
when inside a syscall in the rr page, because the rr page is not
part of any image and does not have CFI info, so the unwinder would
complain.

I originally thought I could just create an ET_EXEC file and ask the
dynamic linker to always map the rr page at the correct address
(preceeded by one page for the ELF header and eh_frame table),
but that turns out to be forbidden. Instead what this does is create
an ET_DYN file and then intercept the initial mmap of said file,
where the dynamic linker expects that kernel to choose a (potentially
randomized) memory location for it. Since we're interposing the
kernel, we can just decide to always map this particular mapping
at the address we want it to be at. Of course, this is somewhat
sensitive to the exact order of events, so while it works well
on my current glibc version, I wouldn't be surprised if other libcs
(or future versions of glibc) may do things differently enough to
not trigger these heuristics. Fortunately, we can just simply keep
doing nothing in that case and while we will see the unwind issue again,
the recording should otherwise be unaffected.

Since we now have a probler .so for the rr_page, the generation process
has changed. Rather than generating the raw bytes using python,
the rr page is now a simple assembly file that contains the appropriate
instructions as well as a link script that ensures the layout is
consistent and known. I also combined the record and replay pages
into one file, with rr deciding to either map the second or third page
of `librrpage.so` as its rr_page. That's not strictly necessary, but
it seemed simplest to me. It also occurred to me that we could also
combine the exec_stub into this file as well to cut down the number
of executable files we need to ship (and have the kernel already
map the rr page for us), but that's just a random side note.

To test this, I'm asking the C++ unwinder to unwind us out of a system
call. Of course, in the real application, the unwinder in question
may not necessarily be the C++ system unwinder (since the unwinder
is explicitly swappable), but it's an easy way to test the issue.
It does assume that whatever libc is in regular use does come
with unwind info, which is the case on most distros I know,
but we can revisit the issue if we get reports that some
distros do not turn on unwind info for their libcs.

cc @staticfloat

### CODE REVIEW

**Comment by rocallahan** [comment]
Looks great to me! Thanks!

**Comment by yuyichao** [comment]
@Keno This breaks `make install`. It seems that the `rr_page_*` files are still being installed but are not being generated anymore. What should be the correct new installation rules?

**Comment by yuyichao** [comment]
And build log ... https://build.archlinuxcn.org/~imlonghao/log/rr-git/2020-12-01T09:03:01.html

**Comment by Keno** [comment]
Sorry, the `rr_page` files aren't used anymore (replaced by librrpage.so). I may have missed an install rule somewhere in the CMake config. Will take a look shortly.

**Comment by yuyichao** [comment]
I assume the missed installation rule is the one ~L660 right below where the installation rule for `rr/src/preload` was added...

**Comment by Keno** [comment]
Yep, I think those should go. Sorry - I thought I had deleted them.

**Comment by khuey** [comment]
This doesn't work on Ubuntu 18.04.

**Comment by khuey** [comment]
https://github.com/rr-debugger/rr/commit/22f34a8e4267f7e82295b7ab49f083a72b21fe2a

**Comment by Keno** [comment]
Thanks for catching that. I rarely use chaos mode, so I never saw this ... Sorry!

**Comment by khuey** [comment]
No worries.

**Pull request merged**
