### PR TITLE
block exit syscalls in diversion from destroying the session

### PR DESCRIPTION
**Pull request by vtjnash**
This PR may be a bit of a tradeoff. Without this PR, a gdb `call` which reaches exit will also destroy the session entirely killing debugging entirely. However, a gdb `call` which reaches a breakpoint and then reaches exit will stop successfully. With this PR, the former will now exit correctly, while the latter will try to re-stop on that deadly signal and hang the session.

I think that is intentional behavior in gdb (it seems to effectively disable unwindonsignal if it reaches a breakpoint during the call), though probably quite undesirable for rr.

See prior attempt and discussion in e627c19b0aaf7f18207cc1ce4d019f4b9ffe603b.

A better approach might be to somehow convince gdb that this function is named std::terminate?

To try out this, see the difference between
```
(rr) call (void) _exit(0)
```
vs.
```
(rr) b _exit
(rr) call (void) _exit(0)
```

### CODE REVIEW

**Comment by rocallahan** [comment]
> Without this PR, a gdb call which reaches exit will also destroy the session entirely killing debugging entirely. 

I'm not sure what you mean by "destroy the session entirely". On rr master, if I do a `call _exit(0)`, that call terminates but I return to the debugging session just fine and I can carry on debugging.

**Comment by vtjnash** [comment]
Okay, maybe that is gdb version specific? Here is what it seems to do for me on rr master:
```
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
rr version 5.5.0
```
```
$ ./bin/rr record true

$ ./bin/rr replay -- -q
Reading symbols from /bin/true...
(No debugging symbols found in /bin/true)
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
Really redefine built-in command "jump"? (y or n) [answered Y; input not from terminal]
Remote debugging using 127.0.0.1:16007
Reading symbols from /lib64/ld-linux-x86-64.so.2...
Reading symbols from /usr/lib/debug//lib/x86_64-linux-gnu/ld-2.31.so...
0x00007f7831a1c100 in _start () from /lib64/ld-linux-x86-64.so.2
(rr) p (void) _exit(0)

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
[New Thread 1106190.1106190]
The program being debugged stopped while in a function called from GDB.
Evaluation of the expression containing the function
(__GI__exit) will be abandoned.
When the function is done executing, GDB will silently stop.
(rr) bt
The current thread has terminated
```

**Comment by rocallahan** [comment]
gdb 9.2 is pretty old. I'm using 12.1.
```
[roc@localhost src]$ rr record true
rr: Saving execution to trace directory `/home/roc/.local/share/rr/true-0'.
[roc@localhost src]$ rr replay -- -q
Warning: /usr/local/lib/rustlib/etc: No such file or directory.
Reading symbols from /home/roc/.local/share/rr/true-0/mmap_clone_5_true...
Reading symbols from /usr/lib/debug/usr/bin/true-9.0-5.fc36.x86_64.debug...
Really redefine built-in command "restart"? (y or n) [answered Y; input not from terminal]
Really redefine built-in command "jump"? (y or n) [answered Y; input not from terminal]
Remote debugging using 127.0.0.1:58019
Reading symbols from /lib64/ld-linux-x86-64.so.2...
BFD: warning: system-supplied DSO at 0x6fffd000 has a section extending past end of file
0x00007f8aa7836d10 in _start () from /lib64/ld-linux-x86-64.so.2
(rr) p (void) _exit(0)

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
[New Thread 909978.909978]
The program being debugged stopped while in a function called from GDB.
Evaluation of the expression containing the function
(__GI__exit) will be abandoned.
When the function is done executing, GDB will silently stop.
(rr) where
#0  0x00007f8aa7836d10 in _start () from /lib64/ld-linux-x86-64.so.2
#1  0x0000000000000001 in ?? ()
#2  0x00007fffeadf2cb3 in ?? ()
#3  0x0000000000000000 in ?? ()
```
Maybe try building or installing a newer gdb and retry?

**Comment by vtjnash** [comment]
Yep, seems to work for me in newer gdb. Sorry for the hassle

**Pull request closed without merging**
