### PR TITLE
Limit CPU choices to the CPUs that are actually online

### LINKED ISSUE #3175: Recording occasionally attempts to bind to non-existant CPU
Recently I've been running into an intermittent situation where I get an error like:

```
pid:742072 [FATAL /home/nika/src/rr/rr/src/[Session.cc:758](http://session.cc:758/):do_bind_cpu() errno: EINVAL] Can't bind to requested CPU 68, and CPUID faulting not available
```

This appears to be being caused by rr selecting a CPU which is outside of the range of actually available CPUs on a Zen system. This machine only has 64 CPUs, so CPU 68 does not exist.

From looking into the source more it appears this is due to the logic in `get_cgroup_cpus`, which queries the `/proc` directory to read the `Cpus_allowed_list`, which on my system reports that CPUs which aren't physically present are allowed. Specifically:

```
$ cat /proc/cpuinfo | grep processor | wc -l
64
$ cat /proc/self/status | grep 'Cpus_allowed'
Cpus_allowed:   ffffffff,ffffffff,ffffffff,ffffffff
Cpus_allowed_list:      0-127
```

It may be necessary to perform an intersection check when reading `Cpus_allowed_list` to make sure that the CPU which we pick is actually present on the system before trying to set thread affinity, especially on zen where we CPUID faulting is not available.

### PR DESCRIPTION
**Pull request by rocallahan**
Resolves #3175

### CODE REVIEW

**Comment by rocallahan** [comment]
@Keno does this make sense to you?

**Comment by Keno** [comment]
The code makes, sense, but you'll frequently be in a situation where `/sys` isn't mapped, so I think there needs to be a retry around the setaffinity also.

**Comment by rocallahan** [comment]
Hmm, what if we throw a `sched_getaffinity()` call in here too? Would that be enough?

It would be extra sad if the only reliable thing to do is to try `sched_setaffinity()` for all possible CPUs :-(

**Comment by rocallahan** [comment]
Adding a retry loop around setaffinity in Session.cc kinda breaks the layering here so I hope this is actually enough.

**Comment by rocallahan** [comment]
I suppose `choose_cpu` could fork a thread and try to bind it to the chosen CPU and retry if that fails. But that's horrible too.

**Comment by Keno** [comment]
This looks reasonable to me and I think it'll solve #3175, though I think #3122 will still be an issue if running in a container without `/sys`. I'm not sure there's any way around refactoring the layering to pass the whole list of cpus through and then throwing a retry loop around the random selection and setaffinity call.

**Comment by rocallahan** [comment]
`sched_getaffinity()` is filtered to the "active" CPUs, which is almost the same set as "online". I think just using that should work pretty well.

**Comment by rocallahan** [comment]
`sched_getaffinity` also takes account of the task's `cpus_mask` which is what `Cpus_allowed_list` shows. So I think we can actually simplify things here.

**Review by Keno — APPROVED** [review]

**Pull request merged**
