### PR TITLE
Run CI on `aarch64` (in addition to `x86_64`)

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by DilumAluthge** [comment]
@Keno I'm seeing a lot of test failures on `aarch64`, but I'm not sure if that's related to how I built the rootfs image.

For aarch64, I built the rootfs image with the `g++` apt package, because the `g++-multilib` apt package was not available on `aarch64`.

For x86_64, the rootfs image was built with the `g++-multilib` apt package.

**Comment by yuyichao** [comment]
On Apple M1 with a few other fixes there are ~30 test failures (more than half of them are due to syscallbuf which I'm looking at). I assume the CI is for neoverse-n1 though, which I don't have access to but most of the test failure shouldn't be microarch dependent. If you want to run julia under rr, currently you may also need a fully clone target for >= v8.1-a that you can use. The cloning logic needs to be fixed to remove that requirement....

**Comment by DilumAluthge** [comment]
@Keno Could you take a look at the failures here? It might be something simple, e.g. maybe we just need to make a few additional modifications to the sandbox code.

**Comment by yuyichao** [comment]
For a start it seems that the sysfs isn’t accessible

**Comment by khuey** [comment]
What does `ls /sys/devices/system/cpu/cpu0/regs/identification/` say on this system?

**Comment by Keno** [comment]
Yes, @DilumAluthge, you'll need to modify the sandbox setup to map in sysfs.

**Comment by yuyichao** [comment]
FWIW, if you want to try trigger the test again. I should have added enough fallback paths in https://github.com/rr-debugger/rr/pull/3217 that would allow this to run without /sys, as long as /proc is available. (this only works for single PMU type).

**Comment by Keno** [comment]
```
[FATAL src/PerfCounters.cc:702:read_ticks()] 5 (speculatively) executed strex instructions detected.
On aarch64, rr only supports applications making use of LSE
atomics rather than legacy LL/SC-based atomics.
Aborting. Retry with -F to override, but replaying such
a recording will probably fail.
```
We need to figure out how to setup the CI system to require lse. @yuyichao Can you advise what needs to happen?

**Comment by yuyichao** [comment]
I don't think you need moutline-atomics for building rr. You already pass armv8.3-a so it should already be using the lse atomics if inlined. (Also, without syscallbuf (or even with it) I don't think much of the code in rr actually use atomics. It's probably mostly the libc code and linker that uses them.)

What you need is to make sure the libraries are built with outline-atomics (or lse FWIW). On ArchLinuxARM this seems to be the default so I really didn't need to do anything on my system.

Depending on the distro you are using and/or where you get all the binaries from, you may either need to install the right packages for the LSE atomic version or maybe find a distro/build that has outline atomics (mostly glibc).

Depending on your distro version, it seems that some distro (used to) ship the different versions with different prefix and although the correct libc.so can get dynamically loaded with magic, the linker doesn't work like that. If that's the case you may need to specify the linker path. Ref https://github.com/rr-debugger/rr/pull/3145 that setting is distro dependent (unneeded on arch linux and apparently needed on some older version of debian/ubuntu).

**Comment by Keno** [comment]
The CI image is debian testing 
```
$ /lib/ld-linux-aarch64.so.1 --version                      
ld.so (Debian GLIBC 2.33-7) release release version 2.33.
Copyright (C) 2021 Free Software Foundation, Inc.
```
My understanding is that outline-atomics should work after glibc 2.31 in debian

**Comment by yuyichao** [comment]
If this is a similar setup to `armageddon.julialang.io` then it seems that the default libc doesn't use outline atomics. I just did a `objdump -d /usr/lib/aarch64-linux-gnu/libc-2.31.so  | grep -10 'stxr'` and these instructions appears in normal functions.

**Comment by yuyichao** [comment]
K, so not the same as the ubuntu used on the host... what does `objdump -d /lib/ld-linux-aarch64.so.1 | grep -10 'stxr'` say?

On my working system, they only appears in `__aarch64_*_*` functions for outline atomics.

**Comment by Keno** [comment]
```
$ objdump -d /lib/ld-linux-aarch64.so.1 | grep -10 'stxr'
   1bcf0:	d503245f 	bti	c
   1bcf4:	900000f0 	adrp	x16, 37000 <_rtld_global+0xfc0>
   1bcf8:	394a8210 	ldrb	w16, [x16, #672]
   1bcfc:	34000070 	cbz	w16, 1bd08 <__aarch64_cas4_acq+0x18>
   1bd00:	88e07c41 	casa	w0, w1, [x2]
   1bd04:	d65f03c0 	ret
   1bd08:	2a0003f0 	mov	w16, w0
   1bd0c:	885ffc40 	ldaxr	w0, [x2]
   1bd10:	6b10001f 	cmp	w0, w16
   1bd14:	54000061 	b.ne	1bd20 <__aarch64_cas4_acq+0x30>  // b.any
   1bd18:	88117c41 	stxr	w17, w1, [x2]
   1bd1c:	35ffff91 	cbnz	w17, 1bd0c <__aarch64_cas4_acq+0x1c>
   1bd20:	d65f03c0 	ret
   1bd24:	d503201f 	nop
   1bd28:	d503201f 	nop
   1bd2c:	d503201f 	nop

000000000001bd30 <__aarch64_swp4_acq>:
   1bd30:	d503245f 	bti	c
   1bd34:	900000f0 	adrp	x16, 37000 <_rtld_global+0xfc0>
   1bd38:	394a8210 	ldrb	w16, [x16, #672]
   1bd3c:	34000070 	cbz	w16, 1bd48 <__aarch64_swp4_acq+0x18>
   1bd40:	b8a08020 	swpa	w0, w0, [x1]
   1bd44:	d65f03c0 	ret
   1bd48:	2a0003f0 	mov	w16, w0
   1bd4c:	885ffc20 	ldaxr	w0, [x1]
   1bd50:	88117c30 	stxr	w17, w16, [x1]
   1bd54:	35ffffd1 	cbnz	w17, 1bd4c <__aarch64_swp4_acq+0x1c>
   1bd58:	d65f03c0 	ret
   1bd5c:	d503201f 	nop

000000000001bd60 <__aarch64_swp4_rel>:
   1bd60:	d503245f 	bti	c
   1bd64:	900000f0 	adrp	x16, 37000 <_rtld_global+0xfc0>
   1bd68:	394a8210 	ldrb	w16, [x16, #672]
   1bd6c:	34000070 	cbz	w16, 1bd78 <__aarch64_swp4_rel+0x18>
   1bd70:	b8608020 	swpl	w0, w0, [x1]
```

**Comment by Keno** [comment]
```
p (int)__aarch64_have_lse_atomics
$3 = 1
```
Detection seems to be working also. Let me me look if there are other libraries that don't have outline-atomics.

**Comment by yuyichao** [comment]
Seems that it should work then...... I hope I didn't do anything stupid and messed up the perf counter ID during refactoring....

**Comment by yuyichao** [comment]
I downloaded the package from https://packages.debian.org/bookworm/arm64/libc6/download and I see similar disassembly for both libc and ld.

**Comment by yuyichao** [comment]
> Let me me look if there are other libraries that don't have outline-atomics.

Just try to record `bin/simple`? I don't think most of the test loads any other libraries....

**Comment by Keno** [comment]
```
$ ./bin/rr record ./bin/simple
rr: Saving execution to trace directory `/home/juliaci/.local/share/rr/simple-1'.
[FATAL src/PerfCounters.cc:702:read_ticks()] 5 (speculatively) executed strex instructions detected. 
On aarch64, rr only supports applications making use of LSE
atomics rather than legacy LL/SC-based atomics.
Aborting. Retry with -F to override, but replaying such
a recording will probably fail.
```
Note that the CI machine is armageddon, but with a special rootfs.

**Comment by yuyichao** [comment]
And if you can easily recompile rr there, maybe try an older version or at least try making replacing the `"armv8_pmuv3_0"` in `PerfCounter.cc` to `nullptr` to force it to use the RAW event type instead? I don't think this should matter though...

FWIW, my earlier build on that machine seems to be working in the host environment....

**Comment by Keno** [comment]
> FWIW, my earlier build on that machine seems to be working in the host environment....

Yes, I see it working in the host environment also

**Comment by yuyichao** [comment]
Current master seems to work at least for `bin/rr bin/simple` in the host env on the same machine so I think it's unlikely that the counters are wrong/lying.

**Comment by yuyichao** [comment]
Do the counters get enabled before rr does exec? Maybe check libstdc++?

**Comment by yuyichao** [comment]
Atomics in https://packages.debian.org/bookworm/arm64/libstdc++6/download seems to be correctly outlined.

**Comment by Keno** [comment]
Let me program the counter to overflow and attach the emergency debugger. Should at least tell us the general vicinity of the issue.

**Comment by Keno** [comment]
Looks like the lse atomics detection happens too late:
```
Breakpoint 1, 0x0000fffff7fac420 in __aarch64_cas4_acq () from /lib/aarch64-linux-gnu/libpthread.so.0
(gdb) p (int)__aarch64_have_lse_atomics
$1 = 0
(gdb) b main
Breakpoint 2 at 0xaaaaaaaaa9c0: file /build/rr/src/test/simple.c, line 6.
(gdb) c
Continuing.

Breakpoint 1, 0x0000fffff7f2b150 in __aarch64_cas4_acq () from /lib/aarch64-linux-gnu/libc.so.6
(gdb) p (int)__aarch64_have_lse_atomics
$2 = 0
(gdb) c
Continuing.

Breakpoint 1, 0x0000fffff7f2b150 in __aarch64_cas4_acq () from /lib/aarch64-linux-gnu/libc.so.6
(gdb) 
Continuing.

Breakpoint 2, main () at /build/rr/src/test/simple.c:6
6	  atomic_puts("EXIT-SUCCESS");
(gdb) p (int)__aarch64_have_lse_atomics
$3 = 1
```

**Comment by Keno** [comment]
It gets initialized here in libc:
```
#0  0x0000fffff7e3e520 in init_have_lse_atomics () from /lib/aarch64-linux-gnu/libc.so.6
#1  0x0000fffff7fd627c in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0xfffffffffd48, 
    env=env@entry=0xfffffffffd58) at dl-init.c:74
#2  0x0000fffff7fd6374 in call_init (env=0xfffffffffd58, argv=0xfffffffffd48, argc=1, l=<optimized out>) at dl-init.c:37
#3  _dl_init (main_map=0xfffff7fff2b0, argc=1, argv=0xfffffffffd48, env=0xfffffffffd58) at dl-init.c:121
#4  0x0000fffff7fc8dc8 in _dl_start_user () from /lib/ld-linux-aarch64.so.1
```
but it gets used before that in ld.so:
```
#0  0x0000fffff7fac420 in __aarch64_cas4_acq () from /lib/aarch64-linux-gnu/libpthread.so.0
#1  0x0000fffff7f9dae0 in __pthread_initialize_minimal_internal () at nptl-init.c:316
#2  0x0000fffff7f9d0e8 in _init () at ../sysdeps/aarch64/crti.S:88
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by yuyichao** [comment]
Here it is initialized in ld

```
(rr) p (int*)&__aarch64_have_lse_atomics
$1 = (int *) 0xfffee9a0d340 <__aarch64_have_lse_atomics>
(rr) p *$1
$2 = 0
(rr) watch -l *$1
Hardware watchpoint 1: -location *$1
(rr) rwatch -l *$1
Hardware read watchpoint 2: -location *$1
(rr) c
Continuing.

Hardware watchpoint 1: -location *$1

Old value = 0
New value = 1
0x0000fffee99d1f68 in init_have_lse_atomics () from /lib/ld-linux-aarch64.so.1
(rr) bt
#0  0x0000fffee99d1f68 in init_have_lse_atomics () from /lib/ld-linux-aarch64.so.1
#1  0x0000fffee99d5a14 in call_init () from /lib/ld-linux-aarch64.so.1
#2  0x0000fffee99d5b1c in _dl_init () from /lib/ld-linux-aarch64.so.1
#3  0x0000fffee99e8258 in _dl_start_user () from /lib/ld-linux-aarch64.so.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by khuey** [comment]
> > Let me me look if there are other libraries that don't have outline-atomics.
> 
> Just try to record `bin/simple`? I don't think most of the test loads any other libraries....

You probably want to test something with threads. I ran into issues on Ubuntu where the dynamic linker (which was *not* replaced by libc6-lse) used the old style atomics but only when threads were involved.

**Comment by Keno** [comment]
> Here it is initialized in ld

Hmm, looks like the source for it is in libgcc [1]. How does it decide where to put it?

[1] https://github.com/RTEMS/gnu-mirror-gcc/blob/master/libgcc/config/aarch64/lse-init.c

**Comment by Keno** [comment]
Hmm no, there's a copy in ld as well:
```
$ objdump -d /lib/ld-linux-aarch64.so.1 | grep init_have_lse_atomics
0000000000000d00 <init_have_lse_atomics>:
```

**Comment by yuyichao** [comment]
Does your ld have such a function?

**Comment by yuyichao** [comment]
For me, my ld and libc both has that function, which is what I'd expect (if they link to the libgcc static library)

**Comment by Keno** [comment]
Ah, it does run, but it runs after libpthread:
```
Breakpoint 1, 0x0000fffff7d3f61c in init_have_lse_atomics () from /lib/aarch64-linux-gnu/libpthread.so.0
(gdb) bt
#0  0x0000fffff7d3f61c in init_have_lse_atomics () from /lib/aarch64-linux-gnu/libpthread.so.0
#1  0x0000fffff7fd627c in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0xfffffffffd58, 
    env=env@entry=0xfffffffffd68) at dl-init.c:74
#2  0x0000fffff7fd63c4 in call_init (env=0xfffffffffd68, argv=0xfffffffffd58, argc=1, l=<optimized out>) at dl-init.c:37
#3  _dl_init (main_map=0xfffff7fff2b0, argc=1, argv=0xfffffffffd58, env=0xfffffffffd68) at dl-init.c:88
#4  0x0000fffff7fc8dc8 in _dl_start_user () from /lib/ld-linux-aarch64.so.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
(gdb) c
Continuing.

Breakpoint 1, 0x0000fffff7fc8d0c in init_have_lse_atomics () from /lib/ld-linux-aarch64.so.1
(gdb) bt
#0  0x0000fffff7fc8d0c in init_have_lse_atomics () from /lib/ld-linux-aarch64.so.1
#1  0x0000fffff7fd627c in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0xfffffffffd58, 
    env=env@entry=0xfffffffffd68) at dl-init.c:74
#2  0x0000fffff7fd6374 in call_init (env=0xfffffffffd68, argv=0xfffffffffd58, argc=1, l=<optimized out>) at dl-init.c:37
#3  _dl_init (main_map=0xfffff7fff2b0, argc=1, argv=0xfffffffffd58, env=0xfffffffffd68) at dl-init.c:121
#4  0x0000fffff7fc8dc8 in _dl_start_user () from /lib/ld-linux-aarch64.so.1
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

**Comment by yuyichao** [comment]
I don't have debug symbol for my ld but it seems like ld initializes itself the first here. (It calls the init_have_lse_atomics in ld the first time it runs `call_init`). Not sure what determines this order though...

**Comment by Keno** [comment]
Ok, so looks like this symbol is duplicated in each .so and `__pthread_initialize_minimal_internal` uses atomics, but is also annotated `attribute((constructor))` and the order in which these run is undefined so the linker just picks one that it likes and one of them works and one of them doesn't.... Sigh. I don't even think we're guaranteed that this will keep working across rebuilds from the same source.

**Comment by yuyichao** [comment]
(As a side note, it seems that on the host there are also ~200 test failure caused by not using LSE atomics... mostly seems to be thread related so potentially related to what @khuey said)

**Comment by yuyichao** [comment]
I guess since this is a static variable, it doesn't matter whether or not the ld initializer runs first?

So inject the value into the library if we can find it? ;-p

**Comment by Keno** [comment]
I was gonna say I don't think it's reasonably possible for us to do that, but seems like we might be able to do it with an audit library. Still, it would be good to work with upstream to come up with a more general solution. I think every application that uses atomics in the constructor will potentially have this issue - i.e. it's not restricted to pthread.

**Comment by Keno** [comment]
My suggestion on how to proceed here is:
1. For now/CI, build a version of the debian libc with `-mno-outline-atomics` and a sufficiently high march to force lse atomics - replacing the libc in the sysimg
2. In general, submit a patch to libgcc to set the init_lse_atomics constructor to priority 100 (i.e. system library priority), which should force it to run sufficiently early to address this concern in most cases.

Thoughts?

**Comment by yuyichao** [comment]
The short term plan sounds good and the long term solution sounds easy enough (I don’t know that there’s a priority that one can play with…). I do feel like that it should be possible to lazy initialize the flag without too much runtime overhead so that this will never be a pro no matter where it is used. (This is my normal solution to fix global initialization order issues…..)

**Comment by Keno** [comment]
I have filed https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105708 to discuss options for an upstream fix with the GCC maintainers. In the meantime, a glibc binary build that's compatible is making its way through the queue at https://github.com/JuliaPackaging/Yggdrasil/pull/4937

**Comment by rocallahan** [comment]
Thanks.

I wonder if we could have rr somehow ensure that `__aarch64_have_lse_atomics` is set early. Is there a symbol for it that we can detect when we map glibc?

**Comment by Keno** [comment]
> I wonder if we could have rr somehow ensure that `__aarch64_have_lse_atomics` is set early. Is there a symbol for it that we can detect when we map glibc?

If there was only only copy of it, I think that'd have been reasonable, but unfortunately, there's one copy per shared object and the visibility is also hidden, so if symbols are stripped, we won't be able to find it.

**Comment by Keno** [comment]
Turns out LLVM already sets constructor priority on this function: https://github.com/llvm/llvm-project/blob/main/compiler-rt/lib/builtins/cpu_model.c#L21 (to 101 rather than 100, but we can submit a patch to align with gcc once they decide what to do).

**Comment by DilumAluthge** [comment]
@Keno We need to either:
1. Change the `wget` invocation to a `curl` invocation
2. Add `wget` to the rootfs image

**Comment by Keno** [comment]
jinx. I changed it to curl just as you posted that.

**Comment by Keno** [comment]
Hmm, the mechanism works, but the libc is still bad. Something must have gotten messed up in the flags in the recipe. I tested it locally and it did work. Let me take another look.

**Comment by Keno** [comment]
Yay, this seems to be working now. TODO list from my perspective:
- [ ] Make the Glibc replacement aarch64 only
- [ ] Adjust the parallelism on aarch64 to match the core count of the container
- [ ] (Optional) aarch64-specific test cost file
- [ ] Make the aarch64 status may-fail, since we still have a number of known failures

@DilumAluthge can you push this through from here? If so I'll drop this from my todo list.

**Comment by Keno** [comment]
libgcc issue is now fixed, so once distributions pick this up and rebuild the world, things should work out of the box: https://github.com/gcc-mirror/gcc/commit/75c4e4909ae2667f56487434f99c2915b4570794. I'll submit a patch to align LLVM at level 90 also, to make sure that we don't get any rude surprises down the line

**Comment by Keno** [comment]
LLVM priority change is at https://reviews.llvm.org/D126424

**Comment by Keno** [comment]
Heh, turns out LLVM's setting of the init priority was accidentally not working - good that we checked or this would have come back to bite us in a few months' time.

**Comment by DilumAluthge** [comment]
@Keno x86_64 is failing?

**Comment by DilumAluthge** [comment]
Ah we just need to not download the libc override on x86_64

**Comment by DilumAluthge** [comment]
The Armageddon machine has 80 cores, and we run 8 Buildkite agents on it, so each job should use no more than 10 xores

**Comment by DilumAluthge** [comment]
> TODO list from my perspective:
> 
> * [ ]  Make the Glibc replacement aarch64 only

Done.

> * [ ]  Adjust the parallelism on aarch64 to match the core count of the container

Done.

> * [ ]  (Optional) aarch64-specific test cost file

Not done. I figure we can do this in a follow-up PR?

> * [ ]  Make the aarch64 status may-fail, since we still have a number of known failures

Done.

**Comment by Keno** [comment]
Can we drop the aarch64 status from GitHub reporting while it's may-fail? Or at least give it a gray thing rather than the red x.

**Comment by DilumAluthge** [comment]
> Can we drop the aarch64 status from GitHub reporting while it's may-fail? Or at least give it a gray thing rather than the red x.

I couldn't figure out how to make it gray, so I just dropped it.

**Comment by DilumAluthge** [comment]
I opened https://github.com/rr-debugger/rr/issues/3244 so we don't forget to do arch-specific CI cost files in a follow-up PR.

**Comment by DilumAluthge** [comment]
@yuyichao This is what I now have on aarch64 CI. Is this list of failures consistent with what you see locally? If so, I think this PR is good to go.

```
97% tests passed, 40 tests failed out of 1313
Total Test time (real) = 961.04 sec
The following tests FAILED:
  200 - futex_restart_race (Failed)
  201 - futex_restart_race-no-syscallbuf (Failed)
  792 - vm_readv_writev (Failed)
  793 - 
vm_readv_writev-no-syscallbuf (Failed)
  832 - async_signal_syscalls (Failed)
  834 - async_signal_syscalls2 (Failed)
  836 - async_signal_syscalls_siginfo (Failed)
  900 - early_error (Failed)
  901 - early_error-no-syscallbuf (Failed)
  938 - hooks (Failed)
  980 - morestack_unwind (Failed)
  992 - patch_page_end (Failed)
  1024 - rseq_syscallbuf (Failed)
  1028 - seccomp_blocks_rr (Failed)
  1072 - term_trace_reset (Failed)
  1073 - term_trace_reset-no-syscallbuf (Failed)
  1074 - term_trace_syscall (Failed)
  1075 - term_trace_syscall-no-syscallbuf (Failed)
  1076 - thread_exit_signal (Failed)
  1077 - thread_exit_signal-no-syscallbuf (Failed)
  1094 - vdso_clock_gettime_stack (Failed)
  1096 - vdso_gettimeofday_stack (Failed)
  1098 - vdso_time_stack (Failed)
  1110 - watchpoint_at_sched (Failed)
  1111 - watchpoint_at_sched-no-syscallbuf (Failed)
  1114 - watchpoint_no_progress (Failed)
  1115 - watchpoint_no_progress-no-syscallbuf (Failed)
  1174 - desched_ticks (Failed)
  1206 - nested_detach_kill (Failed)
  1207 - nested_detach_kill-no-syscallbuf (Failed)
  1226 - replay_serve_files (Failed)
  1227 - replay_serve_files-no-syscallbuf (Failed)
  1252 - reverse_watchpoint (Failed)
  1253 - reverse_watchpoint-no-syscallbuf (Failed)
  1254 - reverse_watchpoint_syscall (Failed)
  1255 - reverse_watchpoint_syscall-no-syscallbuf (Failed)
  1262 - seekticks (Failed)
  1263 - seekticks-no-syscallbuf (Failed)
  1292 - term_trace_cpu (Failed)
  1293 - term_trace_cpu-no-syscallbuf (Failed)
Errors while running CTest
[ Info: Command returned 8
```

**Comment by Keno** [comment]
Good to go I think. Those test failures will get fixed over time, but for now, let's merge this to make sure everything keeps running.

**Comment by Keno** [comment]
The constructor priority change is merged in LLVM also. https://github.com/llvm/llvm-project/commit/167fb106d28ff026f53a3f3468bdcb914e094bd1

**Comment by yuyichao** [comment]
For the record, the failures that I don't have locally are,

```
vm_readv_writev{,-nosyscallbuf}
early_error{,-nosyscallbuf}
term_trace_reset{,-nosyscallbuf}
term_trace_syscall{,-nosyscallbuf}
thread_exit_signal{,-nosyscallbuf}
nested_detach_kill{,-nosyscallbuf}
term_trace_cpu{,-nosyscallbuf}
```

**Comment by yuyichao** [comment]
@DilumAluthge Quite a few of the test failure are actually due to the lack of `pidof` command. (see https://buildkite.com/julialang/rr/builds/616#0181371d-da42-4646-9156-e3a11b45e7cb/6-17669) It seems to be part of the sysvinit-utils package on debian.

**Pull request merged**
