### PR TITLE
Implement rr replay -e/--goto-exit that stops the replay at the exit of a process

### LINKED ISSUE #3131: feature request: way to start gdb session at end of rr recording
Often when I'm recording a failure with rr, there's a relatively long lead-up to the point of failure, which is right at the end of the trace because the debuggee asserts or crashes. When I then use 'rr replay' I have to sit through the debuggee re-running from the start to the point of failure. It would be nice if rr provided a mechanism for "go directly to the last record you have for the debuggee". If I knew the rr event number I could use the replay '-g' option or the optional argument to the gdb 'run' command, but I typically don't. If those commands accepted some syntax for "last event, whatever that is" that would be a time-saver, I think. (It's tempting to suggest a python-style negative-numbers-mean-count-backwards-from-the-end, but that might be a bit confusing.)

Apologies if this functionality already exists, but I didn't find it mentioned in https://github.com/rr-debugger/rr/wiki/Usage

### PR DESCRIPTION
**Pull request by khuey**
Closes #3131

### CODE REVIEW

**Comment by rocallahan** [comment]
Did this cause `stack_overflow_debug(_32)` to fail in CI?

**Comment by khuey** [comment]
Maybe? Sure seems unlikely though.

**Comment by DilumAluthge** [comment]
Let's retry the job a couple of times and see if the failure is the same each time.

**Comment by khuey** [comment]
Can you run it on the tip of the repo a few times and make sure it passes there?

**Comment by DilumAluthge** [comment]
Yep, I've triggered a few jobs on the tip of master, and they all seem to be passing: https://buildkite.com/julialang/rr

**Comment by rocallahan** [comment]
CI FTW

**Comment by khuey** [comment]
Also C++ FTL

**Pull request merged**
