### PR TITLE
[DONOTMERGE] CI debugging

### PR DESCRIPTION
**Pull request by Keno**

### CODE REVIEW

**Comment by yuyichao** [comment]
The syscallbuf branch had one or two runs where I dumped verbose logs. They seems truncated though and I haven't look too much into them yet.

**Comment by yuyichao** [comment]
I think this was the run https://buildkite.com/julialang/rr/builds/727#0181ad60-e062-4381-97bd-bdbdaa2bb56b

**Comment by Keno** [comment]
Thanks, that is helpful:
```


[Scheduler]   new status is 0x857f (SYSCALL)
--
  | [RecordSession] trace time 1: Active task is 117419. Events:
  | [INFO log_pending_events()] (no pending events)
  | [RecordSession] EXEC_SYSCALL_ENTRY: status=0x857f (SYSCALL)
  | [RecordTask] Wrote event SYSCALL: prctl for time 1
  | [RecordSession] after cont: status=0x857f (SYSCALL)
  | [RecordSession] EXEC_START: status=0x857f (SYSCALL)
  | [Task] resuming execution of 117419 with PTRACE_SYSCALL tick_period -2 wait 1
  | [Scheduler] Scheduling next task (PREVENT_SWITCH)
  | [Scheduler]   (117419 is un-switchable at SYSCALL: prctl)
  | [Scheduler]   and running; waiting for state change
  | [Task] going into blocking waitid(117419) ...
  | [Task]   Task 117419 changed status to 0x857f (SYSCALL)
  | [Task]   (refreshing register cache)
  | [Task] Requesting registers from tracee 117419
  | [Scheduler]   new status is 0x857f (SYSCALL)
  | [RecordSession] trace time 2: Active task is 117419. Events:
  | [INFO log_pending_events()] SYSCALL: prctl
  | [INFO log_pending_events()] (none)
  | [RecordSession] EXEC_IN_SYSCALL: status=0x857f (SYSCALL)
  | [Scheduler] Scheduling next task (PREVENT_SWITCH)
  | [Scheduler]   (117419 is un-switchable at SYSCALL: prctl)
  | [RecordSession] trace time 2: Active task is 117419. Events:
  | [INFO log_pending_events()] SYSCALL: prctl
  | [INFO log_pending_events()] (none)
  | [RecordSession] EXEC_SYSCALL_DONE: status=0x857f (SYSCALL)
  | [RecordSession]   original_syscallno:167 (prctl); return val:0x16
  | [record_syscall] 117419: processing: SYSCALL: prctl -- time: 2
  | [RecordTask] Wrote event SYSCALL: prctl for time 2
  | [Scheduler] Scheduling next task (ALLOW_SWITCH)
  | [Scheduler] Task event is (none)
  | [Scheduler]   117419 isn't blocked
  | [Scheduler]   Carrying on with task 117419
  | [RecordSession] trace time 3: Active task is 117419. Events:
  | [INFO log_pending_events()] (no pending events)
  | [RecordSession] EXEC_START: status=0x857f (SYSCALL)
  | [PerfCounters] Resetting counters with period 1417143
  | [Task] resuFAILED at src/test/early_error.c:76: !(0) errno:0 (Success)


```
This trace doesn't make much sense to me. The seccomp filter should have terminated the tracee with SIGSYS, but it's almost like it instead re-wrote the syscall to execve. I don't get it.

**Comment by Keno** [comment]
Ah, the log was indeed truncated. I managed to run it again with a larger log buffer:
```
[RecordTask] Wrote event SYSCALL: prctl for time 2
[Scheduler] Scheduling next task (ALLOW_SWITCH)
[Scheduler] Task event is (none)
[Scheduler]   2488690 isn't blocked
[Scheduler]   Carrying on with task 2488690
[RecordSession] trace time 3: Active task is 2488690. Events:
[INFO log_pending_events()] (no pending events)
[RecordSession] EXEC_START: status=0x857f (SYSCALL)
[PerfCounters] Resetting counters with period 1152921504606846976
[Task] resuming execution of 2488690 with PTRACE_SYSCALL tick_period -1 wait 1
[Task] Flushing registers for tid 2488690 { ip:0xffffa5008980 args:(0x16,0x2,0xffffe316d570,0,0,4294967288) orig_syscall: 167 syscallno: 167 orig_arg1: 0x16 }
[Scheduler] Scheduling next task (PREVENT_SWITCH)
[Scheduler]   (2488690 is un-switchable at (none))
[Scheduler]   and running; waiting for state change
[Scheduler] Using unlimited ticks mode
[Task]   Task 2488690 changed status to 0x1f7f (STOP-SIGSYS)
[Task]   (refreshing register cache)
[Task] Requesting registers from tracee 2488690
[Scheduler]   new status is 0x1f7f (STOP-SIGSYS)
[RecordSession] trace time 3: Active task is 2488690. Events:
[INFO log_pending_events()] (no pending events)
[WARN handle_signal_event()] Dropping SIGSYS because it can't be delivered yet
[RecordTask] Refreshed sigmask, now 0
[RecordSession] EXEC_START: status=0x1f7f (STOP-SIGSYS)
[PerfCounters] Resetting counters with period 1152921504606846976
[Task] resuming execution of 2488690 with PTRACE_SYSCALL tick_period -1 wait 1
[Scheduler] Scheduling next task (PREVENT_SWITCH)
[Scheduler]   (2488690 is un-switchable at (none))
[Scheduler]   and running; waiting for state change
[Scheduler] Using unlimited ticks mode
[Task]   Task 2488690 changed status to 0x857f (SYSCALL)
[Task]   (refreshing register cache)
[Task] Requesting registers from tracee 2488690
[Scheduler]   new status is 0x857f (SYSCALL)
[RecordSession] trace time 3: Active task is 2488690. Events:
[INFO log_pending_events()] (no pending events)
[RecordSession] EXEC_START: status=0x857f (SYSCALL)
[PerfCounters] Resetting counters with period 1152921504606846976
[Task] resuming execution of 2488690 with PTRACE_CONT tick_period -1 wait 1
[Scheduler] Scheduling next task (PREVENT_SWITCH)
[Scheduler]   (2488690 is un-switchable at (none))
[Scheduler]   and running; waiting for state change
[Scheduler] Using unlimited ticks mode
[Task]   Task 2488690 changed status to 0x4057f (PTRACE_EVENT_EXEC)
[Task]   (refreshing register cache)
[Task] Requesting registers from tracee 2488690
[Scheduler]   new status is 0x4057f (PTRACE_EVENT_EXEC)
[RecordSession] trace time 3: Active task is 2488690. Events:
[INFO log_pending_events()] (no pending events)
[RecordSession]   2488690: handle_ptrace_event PTRACE_EVENT_EXEC: event (none)
[FATAL src/Event.h:348:Syscall()] is_syscall_event()
```

**Comment by Keno** [comment]
```
[WARN handle_signal_event()] Dropping SIGSYS because it can't be delivered yet
```
in particular is the explanation for our problem

**Pull request closed without merging**
